### ISSUE TITLE
基于Zookeeper生成workerId的IdGenerator实现

### ISSUE THREAD

**Issue by xydonne** [shardingjdbc/sharding-jdbc#190]
# 实现
ZkIdGenerator：通过zookeeper维护workerId。使用时需要添加zookeeper客户端curator（curator-framework与curator-recipes）依赖，并设置zkNodes与appName。（将向zookeeper中/snowflake/appName下注册并节点，并通过zookeeper动态维护workerId。）

# 设计思想：
snowflake的ID分三段，前42位时间由NTP来维护，后12位为时间相同时递增。那关键就在维护中间10位的workerID，使之不重复。

配置上参考dubbo的
Zookeeper节点地址配置：
dubbo.registry.address=127.0.0.1:2181,192.168.1.1:2181
如果设置了zookeeper的权限,还需要添加访问权限
在Zookeeper上注册的节点
/dubbo/com.alibaba.dubbo.demo.api.DemoService

这里因为dubbo的consumer要实例化调用的接口对象，所以写的接口类名。
而我们只要节点值唯一就行。所以有两种选择
1. 用表名或者表对应的实体类名，缺点不同表之间的主键会重复。
2. 用应用名，缺点同一应用下主机数不能超过1024。
例如，用应用名，将在Zookeeper上注册的节点，区分不同应用
/snowflake/dubbo.application.name

配置样例
sjdbc.zk.id.generator.zk.nodes=127.0.0.1:2181,192.168.1.1:2181
sjdbc.zk.id.generator.app.name=dubbo.application.name
sjdbc.zk.id.generator.zk.authority=admin:password

同一应用中的机器将在应用名节点下创建瞬时节点，注册自己的workerId
/snowflake/dubbo.application.name/0
/snowflake/dubbo.application.name/1
/snowflake/dubbo.application.name/2
/snowflake/dubbo.application.name/3
/snowflake/dubbo.application.name/4

如果机器断开连接，节点将被删除，列如1号机器断开连接后
/snowflake/dubbo.application.name/0
/snowflake/dubbo.application.name/2
/snowflake/dubbo.application.name/3
/snowflake/dubbo.application.name/4

此时如果有新机器来注册，我们希望它向5号节点注册，而不是注册到1号节点。两方面原因
1. 可能只是1号节点和zk间的网络不通，但能接受前端请求，生成id插入数据库，造成主键重复
2. 1号节点时间并未和新注册的机器时间同步，此时也有可能造成主键重复
/snowflake/dubbo.application.name/0
/snowflake/dubbo.application.name/2
/snowflake/dubbo.application.name/3
/snowflake/dubbo.application.name/5
此种方式就需要记录最新注册节点的id，每次新节点注册成功后，会将workerId的值写入/snowflake/dubbo.application.name节点
新节点注册时获取/snowflake/dubbo.application.name的值，从此值向后进行注册，直到找到空节点

主机断开连接后，此主机节点将被删除，而此主机将不停请求zookeeper，直至注册新节点成功，重新注册成功后将更新主机的workId。

参见
https://github.com/xydonne/sharding-jdbc/tree/id-generator/187

按照规范修改ing。

**Comment by hanahmily** [comment]
基本设计没有问题，我觉得应该把当前进程的主机名+进程编号写入临时节点。既可以调试，也可以代替ctime作为节点是否被覆盖的标志。
另外，需要考虑多进程并发获取id的情况，增加相关判断。

**Comment by xydonne** [comment]
好，是应当把当前进程的主机名+IP+进程编号写入临时节点。
节点被覆盖的标志继续用ctime好了，相对精准，判断上比较简单，不容易出错

**Comment by xydonne** [comment]
重新修改了设计

原节点修改为
/snowflake/dubbo.application.name/node/0
/snowflake/dubbo.application.name/node/1

新增配置节点
/snowflake/dubbo.application.name/config/order
配置节点order值为节点创建的顺序,FIFO,默认值为[0,1,2,3...1022,1023]

应对高并发,会在注册时先对/snowflake/dubbo.application.name节点加锁,等注册完,释放锁.

注册节点时,从order节点列表的第一个元素开始遍历,如果节点还未被注册,则获取节点值进行注册.

注册时,将当前的ip,hostName,pid写入需要注册的节点

当第一个节点注册后,order节点的值变为[1,2,3,4...1022,1023,0]


参见:
https://github.com/xydonne/sharding-jdbc/tree/id-generator/190

已提价PR

**Comment by hanahmily** [comment]
2.0版本后，内部结构发生变化，故放弃该版本合并
