### ISSUE TITLE
分库和分表索引宽度可配置

### ISSUE THREAD

**Issue by qiaosonghz** [shardingjdbc/sharding-jdbc#220]
[建议描述]
表索引支持固定宽度如table_012 而不是table_12。 
[行为模式]
解决阿里云drds 表索引为固定宽度的问题。
目前阿里云数据库rds使用比较广泛，分库分表后dml 可使用sharding-jdbc, 然而ddl 维护库表可能需要阿里云drds。 
[实现方式]
增加配置关键字table-index-width。配置如下
<rdb:table-rule logic-table="table" actual-tables="table_${0..127}" **table-index-width="3"** database-strategy="databaseStrategy" table-strategy="flowTableStrategy"/>

**Comment by qiaosonghz** [comment]
本地做了开发自测， 计划春节前提交pull request。
和张哥做了沟通，预计亮哥节后评估merge。

**Comment by qiaosonghz** [comment]
基于sharding-jdbc1.4.1 版本增加固定宽度支持， 在公司内部已上线并运行3周左右，比较稳定。

**Comment by terrymanu** [comment]
由于该issue半年无反馈，也未收到pr，因此先关闭了。
