### ISSUE TITLE
是否支持动态修改DataSourceRule及ShardingRule..？

### ISSUE THREAD

**Issue by markfredchen** [shardingjdbc/sharding-jdbc#265]
我这里有一个需求是需要动态添加分片数据库，请问现在jdbc-sharding，是否支持把动态新建的分片数据库添加到DataSourceRule，并修改后续ShardingRule?

**Comment by terrymanu** [comment]
暂时还不支持，预计1.6.0时做配置动态化时会支持

**Comment by terrymanu** [comment]
配置动态化预计在1.6.0发布

**Comment by terrymanu** [comment]
fixed at 2.0.0.M1
