### ISSUE TITLE
用sharing-jdbc的example(sharding-jdbc-example-mybatis)往两个数据库插两万条数据   , 比我不用Sharding-jdbc往一个数据库里面插20000数据,要慢3秒钟,是不是我哪里操作错了

### ISSUE THREAD

**Issue by xuanzi200** [shardingjdbc/sharding-jdbc#377]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
使用的是最新的Sharding-Jdbc-1.5.3

![image](https://user-images.githubusercontent.com/17892381/30464119-34a551ae-9a02-11e7-876c-43c687711583.png)

![image](https://user-images.githubusercontent.com/17892381/30464139-5a22aed6-9a02-11e7-9994-43510584301a.png)

### Please provide the reproduce example codes (such as github link) if possible.

https://github.com/xuanzi200/Sharding-JDBC-Used.git

**Comment by xuanzi200** [comment]
麻烦大家看一下

**Comment by yue530tom** [comment]
这位同学 我这边模拟不出你的场景~ 执行insert jdbc 和sjdbc基本都是2ms左右 2w条记录总执行时间均在40000ms+（多次执行的结果）

**Comment by xuanzi200** [comment]
你好,你是按照我上传到GitHub里面的工程来运行的么? 这个工程下面,有两个module,一个是Sharding-jdbc的example,另一个是我写的,

**Comment by xuanzi200** [comment]
@yue530tom 

你好,你是按照我上传到GitHub里面的工程来运行的么? 这个工程下面,有两个module,一个是Sharding-jdbc的example,另一个是我写的,

**Comment by xuanzi200** [comment]
@yue530tom 

如果你是按照我上传到GitHub的工程的话,我用的mysql是5.7的没有,任何优化,不至于差距会这么大

**Comment by yue530tom** [comment]
是的，直接运行你在Github上的工程。从我们性能测试结果来看不存在这么大的差距，具体可以参考2.0.0.m1分支中的测试报告里面有详细的数据记录https://github.com/dangdangdotcom/sharding-jdbc/blob/2.0.0.M1/sharding-jdbc-doc/content/01-start/stress-test.md 具体的图片信息可以查看在https://github.com/dangdangdotcom/sharding-jdbc/tree/2.0.0.M1/sharding-jdbc-doc/static/img

使用down的工程执行2w次插入，Shardingjdbc和jdbc的结果分别如下
`Start : Mon Sep 18 18:08:02 CST 2017
insert first 193ms
forFunc sharding 41011ms
End : Mon Sep 18 18:08:43 CST 2017
Take {41151} ms .`
`Start : Mon Sep 18 18:13:12 CST 2017
insert first 25ms
forFunc jdbc 40226ms
End : Mon Sep 18 18:13:53 CST 2017
Take {40469} ms .`

可以的话可以加下QQ316216160

**Comment by terrymanu** [comment]
因为你的测试数据库中没有数据，因此insert数据的绝对值很快。
对于这条insert sql的损耗在0.6ms左右，而insert的操作仅需1ms，因此看起来损耗率很高。
一般线上数据库，需要分库分表的场景，insert在15ms左右是比较容易接受的，这样0.6ms的损耗率就很低了。
因为解析sql所消耗的时间是定值，因此需要根据场景才能决定这个损耗率是否合理。
单纯的测试空数据库的insert价值并不高。
