### ISSUE TITLE
FIND_IN_SET support 

### ISSUE THREAD

**Issue by denghc0607** [shardingjdbc/sharding-jdbc#385]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.4
### Expected behavior
i look forward to that shardingjdbc  could support the func : "FIND_IN_SET"  later, then it will be wonderful for my work, thanks !
### Actual behavior
can't find in DefaultKeyword.java and MySQLKeyword.java

**Comment by terrymanu** [comment]
we have no plan to support special sql features
