### ISSUE TITLE
支持SELECT 1这种不包含表名称的SQL

### ISSUE THREAD

**Issue by dexter9000** [shardingjdbc/sharding-jdbc#386]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.3
### Expected behavior
在spring boot注入数据源时，org.springframework.boot.actuate.health.DataSourceHealthIndicator会定时执行"SELECT 1"语言监测数据源的连通性
对于不指定表名的数据库访问能够直接访问默认数据源

### Actual behavior
抛出异常Cannot find table rule and default data source with logic tables: '[]'
导致spring的健康检查认为失败
```
db: {
status: "DOWN",
primaryDataSource: {
status: "UP",
database: "H2",
hello: 1
},
multipleDS: {
status: "DOWN",
database: "H2",
error: "com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]'"
}
}
```

**Comment by terrymanu** [comment]
fixed at 2.0.0.m1
