### ISSUE TITLE
order by 多字段expression sql语句重写错误

### ISSUE THREAD

**Issue by renguiqiang** [shardingjdbc/sharding-jdbc#388]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
<version>1.5.4.1</version>
### Expected behavior
 select
    id, ugc_id, subject_id, subject_type, order_id, reply_user_count, upvote  from ugc_info_0
     WHERE (  subject_id = ?
                  and subject_type = ?
                  and parent = ? ) 
      AND  deleted = 0
      order by upvote + 2 * reply_user_count DESC
### Actual behavior
 select
    id, ugc_id, subject_id, subject_type, order_id, reply_user_count, upvote,
   upvote + 2 * reply_user_count DESC AS ORDER_BY_DERIVED_0   from ugc_info_0
     WHERE (  subject_id = ?
                  and subject_type = ?
                  and parent = ? ) 
      AND  deleted = 0
      order by upvote + 2 * reply_user_count DESC

**Comment by terrymanu** [comment]
不支持这样的sql。sharding jdbc用于处理面向互联网的海量数据。请先确定你的sql是否有可能和必要跑在基于两亿数据的查询。相信贵公司的dba不会同意这样的sql通过吧

**Comment by renguiqiang** [comment]
@terrymanu  系统中涉及的表除了两亿多的数据外，也可能会存在小数据量的表，但是系统中引入sharding jdbc + mybatis后，sql语句的解析都会交给sharding-jdbc来处理，这样造成了对小表的排序查询也出现了异常。

**Comment by terrymanu** [comment]
参加faq第10个问题，我想在这个场景同样适用。
shardingjdbc.io/docs/01-start/faq/
