### ISSUE TITLE
循环查询分表，空指针异常

### ISSUE THREAD

**Issue by panhaicheng** [shardingjdbc/sharding-jdbc#389]
条件：
sharding-jdbc  1.5.4
mybatis   3.3.0
mybatis-spring  1.2.3
用sharding-jdbc对某张表做了分表

配置：
![image](https://user-images.githubusercontent.com/19829285/30998312-2a833c5a-a500-11e7-91e2-0f58efb0902f.png)

问题描述：
执行下面伪代码查询，第一次循环查询正常，第二次循环查询报空指针异常：

伪代码
for(String id : voucherGroup){
	Map<String, Object> map = new HashMap<String, Object>();
	map.put("periodId", id);
	int count = accountEntryMapper.selectCountByPeriodId(map);
}

sql
![image](https://user-images.githubusercontent.com/19829285/30907490-5ef85ee2-a3ad-11e7-9a48-e8bade5d2245.png)

异常
![image](https://user-images.githubusercontent.com/19829285/30907448-3d15f924-a3ad-11e7-8570-64db1d10e6dc.png)

**Comment by haocao** [comment]
请在github上提供完整重现DEMO，以便跟进调试。

**Comment by terrymanu** [comment]
未提供版本号，怀疑是版本过旧导致。请用最新版本尝试。如仍有问题，请提供可重现的demo。这个isdue我先关了

**Comment by terrymanu** [comment]
由于长时间无反馈，目前的信息并不足以定位问题。只能怀疑该问题与#387是一个问题，因此先关闭了。
