### ISSUE TITLE
Cannot find table rule and default data source with logic tables: '[]'

### ISSUE THREAD

**Issue by skywalker-76** [shardingjdbc/sharding-jdbc#392]
version 1.5.4.1
报错Cannot find table rule and default data source with logic tables: '[]'
还有inline表达式也不能用
下面是我的配置
<rdb:strategy id="idTableStrategy" sharding-columns="id_card" algorithm-class="com.analysis.algorithm.IdCardTableSharingAlgorithm"/>
    <rdb:data-source id="shardingDataSource">
        <rdb:sharding-rule data-sources="dataSource">
            <rdb:table-rules>
                <rdb:table-rule logic-table="rule_user" actual-tables="rule_user_0,rule_user_1,rule_user_2,rule_user_3,rule_user_4,
                rule_user_5,rule_user_6,rule_user_7,rule_user_8,rule_user_9" table-strategy="idTableStrategy"/>
            </rdb:table-rules>
            <rdb:binding-table-rules>
                <rdb:binding-table-rule logic-tables="rule_user"/>
            </rdb:binding-table-rules>
            <rdb:default-database-strategy sharding-columns="none" algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.database.NoneDatabaseShardingAlgorithm"/>
        </rdb:sharding-rule>
    </rdb:data-source>

**Comment by 595431930** [comment]
描述不够清楚，单看配置应该是没有配置默认数据源！

**Comment by 595431930** [comment]
inline表达式不能使用问题，请阅读官方文档faq章节

**Comment by terrymanu** [comment]
请认真阅读文档后再提问，让问题更有意义
