### ISSUE TITLE
当前不支持对A表查询 WHERE条件中使用了B表的数据

### ISSUE THREAD

**Issue by komawei** [shardingjdbc/sharding-jdbc#395]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.4.1
### Expected behavior
SELECT a.* FROM PU_Order a
WHERE a.orderId IN (SELECT orderId FROM PU_OrderDetail WHERE commodityCode LIKE ‘%aaa%’

PU_Order与PU_OrderDetail配了主从表绑定关系的
<rdb:binding-table-rule logic-tables="PU_Order, PU_OrderDetail" />
这两个表的分片键都是一样的，但是在执行SQL的时候，这个SQL只会变成
SELECT a.* FROM PU_Order_2017 a
WHERE a.orderId IN (SELECT orderId FROM PU_OrderDetail WHERE commodityCode LIKE ‘%aaa%’

后面的PU_OrderDetail还是逻辑表名，并没有去找物理表PU_OrderDetail_2017

请解答，这个是当前不支持这样的子查询，还是bug，谢谢

**Comment by terrymanu** [comment]
不支持这样的子查询，关于何种子查询支持请阅读文档
