### ISSUE TITLE
用户表的主键使用sharding-jdbc的分布式主键问题

### ISSUE THREAD

**Issue by linxiangqian** [shardingjdbc/sharding-jdbc#399]
用户表的主键使用sharding-jdbc的分布式主键问题：

sharding-jdbc的分布式主键生成的是偶数，如果在创建用户的时候，user_id使用sharding-jdbc的分布式主键的时候，如果是只有两个数据库的话，那么求模为奇数的数据库就不会插入数据了，这个怎么破呢？

**Comment by terrymanu** [comment]
请认真阅读文档。http://shardingjdbc.io/docs/01-start/faq/
