### ISSUE TITLE
ExecutorEngine线程池使用守护线程？

### ISSUE THREAD

**Issue by cocodroid** [shardingjdbc/sharding-jdbc#400]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.4.5.1
executorService = MoreExecutors.listeningDecorator(new ThreadPoolExecutor(
                executorSize, executorSize, 0, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(), new ThreadFactoryBuilder().setDaemon(true).setNameFormat("ShardingJDBC-%d").build()));
    
为啥这里setDaemon(true)要设置为true，我设置为false是否有问题呢？如果用户线程都退出了，守护进程也会退出，如果线程池正在处理任务不也是会影响么？

**Comment by terrymanu** [comment]
守护进程会优雅退出。如果用用户进程，sjdbc将永远无法优雅关闭。

**Comment by cocodroid** [comment]
嗯，我做了测试，如果线程池线程是用户线程，那么程序将不会优雅关闭，因为线程还存在。除非触动关闭线程池的操作shutdownNow才行。但是如果是守护线程，那么当其它用户线程全部已经退出，那么程序将会优雅关闭。
