### ISSUE TITLE
对用于分表的字段进行修改后，分页排序查询的问题

### ISSUE THREAD

**Issue by denghc0607** [shardingjdbc/sharding-jdbc#402]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
        1.5.4.1
### Please provide the reproduce example codes (such as github link) if possible.
        
- 你好，我的用于分表的字段是UPDTIME(修改时间)，第一次入库后根据不同的入库时间（UPDTIME）按月份入到对应的分表中存储，期间对9月份的两条记录修改后UPDTIME变化（变成10月10号），在1.5.4.1和1.5.4版本中分页排序（修改时间升序、降序）查询，这修改的两条记录始终在最前面，而且查询的记录数=每页规定数量+2（修改的两条），而且我尝试了用其他字段升降序分页查询，情况依然不变，于是试了之前用过的版本1.5.0和1.5.3，可以得到想要的结果。

**Comment by terrymanu** [comment]
不支持对分片字段进行修改，需要自己进行数据迁移

**Comment by denghc0607** [comment]
- 恩，我做了调整，不对分片字段进行处理，只做路由用，但是1.5.4.1版本的分页应该是有问题的，我在空的11月份和12月份两张空表中分别插入两条数据（UPDTIME符合分片策略），查询sql语句如下:

            select ID from resourcetable where UPDTIME > '2017-11-01' AND UPDTIME < '2017-12-31'  order by UPDTIME desc limit 0,2 

查出来4条结果。而尝试了1.5.3查出预期的两条结果。
