### ISSUE TITLE
官方QQ不给进，只能在这里提个问了。如何让某些表用or，distinct之类的限制

### ISSUE THREAD

**Issue by limjiregister** [shardingjdbc/sharding-jdbc#403]
请问，如何让sharding-jdbc不要对 不分库分表的 sql 产生作用呢？现在用quartz，有一些 or 那些限制在用。不停报错。？？

org.quartz.JobPersistenceException: Failure identifying failed instances when checking-in: Not supported token 'DISTINCT'.

Caused by: com.dangdang.ddframe.rdb.sharding.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'DISTINCT'

如果说没法 区别对 表产生作用，一定要全局的表产生作用？想问问，使用这个东西的人，是如何避免这些限制的？比如quartz，它就自己是那样了，只能舍弃quartz？？那.....

===============================================
刚找到这个描述：

8. 如果只有部分数据库分库分表，是否需要将不分库分表的表也配置在分片规则中？

回答：

是的。因为Sharding-JDBC是将多个数据源合并为一个统一的逻辑数据源。因此即使不分库分表的部分，不配置分片规则Sharding-JDBC即无法精确的断定应该路由至哪个数据源。 但是Sharding-JDBC提供了两种变通的方式，有助于简化配置。

方法1：配置default-data-source，凡是在默认数据源中的表可以无需配置在分片规则中，Sharding-JDBC将在找不到分片数据源的情况下将表路由至默认数据源。

方法2：将不参与分库分表的数据源独立于Sharding-JDBC之外，在应用中使用多个数据源分别处理分片和不分片的情况。

=====================================
这句话如何理解？
所谓默认数据源库，是指完全没有的参与sharding-jdbc的数据库吗？如下，我这里spring_batch_demo_0既有参与sharding的，也有不参与sharding的，即便设置了默认数据，sharding-jdbc还是把所有的表都参与sharding-jdbc，是这样理解吗？

	//配置数据库
		Map<String, DataSource> dataSourceMap = new HashMap<>();
		dataSourceMap.put("spring_batch_demo_0", createDataSource("spring_batch_demo_0"));
		dataSourceMap.put("spring_batch_demo_1", createDataSource("spring_batch_demo_1"));

		//多数据源，配置一个默认的数据库
		DataSourceRule dataSourceRule = new DataSourceRule(dataSourceMap, "spring_batch_demo_0");

此外，方法2 如何操作啊？这句话，分别配置数据源？难道sharding-jdbc不是自己可以配置多数据源的吗？Map<String, DataSource> dataSourceMap = new HashMap<>();，在这里设置一个默认的。还是有别的方式配置独立于sharding-jdbc之外的数据源呢？？

**Comment by windhc** [comment]
使用的Sharding-JDBC版本

**Comment by terrymanu** [comment]
请阅读faq文档http://shardingjdbc.io/docs/01-start/faq/
第八个问题

**Comment by 347154468** [comment]
请问这个现在支持了吗
