### ISSUE TITLE
SQL中无分片字段，如何提高SQL性能？有没有好的思路

### ISSUE THREAD

**Issue by wxl24life** [shardingjdbc/sharding-jdbc#406]
SQL中如果无分片字段，将执行全路由，性能较差。但是实际业务中难免出现这种SQL需求，请问大家是怎么做的？sharding-jdbc对于这类SQL的写法有没有好的建议，或者有没有做性能上的考量？

我们一直的做法是另外建一张映射表，用于维护查询字段与分片字段的映射关系，在执行相关SQL时，先查一次映射表，然后确定具体需要访问的分表。

主要面临的问题，映射表会很大，可能也需要做分表，或者加一层缓存，以提高查询性能。

**Comment by terrymanu** [comment]
无分片键即全路由，业务方面的设计和考量不在讨论范围内。请理解
