### ISSUE TITLE
源码问题

### ISSUE THREAD

**Issue by qmcqyc** [shardingjdbc/sharding-jdbc#408]
路径是：https://github.com/shardingjdbc/sharding-jdbc/blob/master/sharding-jdbc-core/src/main/java/io/shardingjdbc/core/parsing/lexer/analyzer/CharType.java

代码是：
 public static boolean isWhitespace(final char ch) {
        return ch <= 32 && EOI != ch || 160 == ch || ch >= 0x7F && ch <= 0xA0;
    }
问题1： 0xA0==160 ，为啥还要单独判断160 == ch后，又在ch >= 0x7F && ch <= 0xA0判断中有0xA0；
问题2：ch <= 32 && EOI != ch中为啥要排除EOI (26);
问题3：在ch >= 0x7F && ch <= 0xA0中，为啥只到0xA0，后续的字符为啥又不考虑

谢谢！

**Comment by terrymanu** [comment]
这里的代码是参照之前的druid写的。当时没注意看，仔细一看确实不合理，我修改一下

**Comment by terrymanu** [comment]
问题1：已修改为return ch <= 32 && EOI != ch || ch >= 0x7F && ch <= 0xA0;
问题2：判断是否是空格并不包含行结束符
问题3：A0后面不是空格

**Comment by terrymanu** [comment]
fixed at 2.0.0.M2
