### ISSUE TITLE
Oracle 数据库查询Order By异常

### ISSUE THREAD

**Issue by 595431930** [shardingjdbc/sharding-jdbc#411]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.4.1
### Expected behavior
查询按照相应字段进行排序
### Actual behavior
执行"select * from tb_config order by create_time" mysql下运行正常，oralce下异常提示“Order by value must implements Comparable”，查看源码OrderByValue#getOrderValues()发现sharding jdbc在进行结果归并时要求返回类型必须继承Comparable接口，而ojdbc实现JDBC规范并未按照标准实现并未继承Comparable导致运行出错

**Comment by terrymanu** [comment]
我试了一下不能重现，是不是你oracle驱动的问题，我使用的驱动是：

```xml
        <dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc14</artifactId>
            <version>10.2.0.3.0</version>
        </dependency>
```

请提供一下你的驱动。
PS：带date类型排序的测试用例已添加，在https://github.com/shardingjdbc/sharding-jdbc/commit/0f190d470e1237d6bf2dc12128d3216e0f282c38，可随时查看

**Comment by 595431930** [comment]
@terrymanu 感谢亮哥回复，最后我经过不断排查问题发现只有TimeStamp类型会出现这样的问题，经阅读sharding-jdbc源码com.dangdang.ddframe.rdb.sharding.merger.orderby.OrderByValue#getOrderValues()方法如下：
`private List<Comparable<?>> getOrderValues() throws SQLException {
        ArrayList result = new ArrayList(this.orderByItems.size());
        Iterator i$ = this.orderByItems.iterator();

        while(i$.hasNext()) {
            OrderItem each = (OrderItem)i$.next();
            Object value = this.resultSet.getObject(each.getIndex());
            Preconditions.checkState(null == value || value instanceof Comparable, "Order by value must implements Comparable");
            result.add((Comparable)value);
        }

        return result;
    }`
使用了resultSet.getObject(int index)方法，针对TimeStamp oracle会根据oracle.jdbc.J2EE13Compliant属性判断返回java.sql.TimeStamp还是自定义oralce.sql.TIMESTAMP,详见ojdbc源码oracle.jdbc.driver.TimestampAccessor#getObject(int var1)方法：
` Object getObject(int var1) throws SQLException {
        Object var2 = null;
        if(this.rowSpaceIndicator == null) {
            DatabaseError.throwSqlException(21);
        }

        if(this.rowSpaceIndicator[this.indicatorIndex + var1] != -1) {
            if(this.externalType != 0) {
                switch(this.externalType) {
                case 93:
                    return this.getTimestamp(var1);
                default:
                    DatabaseError.throwSqlException(4);
                    return null;
                }
            }

            if(this.statement.connection.j2ee13Compliant) {
                var2 = this.getTimestamp(var1);
            } else {
                var2 = this.getTIMESTAMP(var1);
            }
        }

        return var2;
    }`
针对上面问题解决方式有两种：
1.配置启动JVM参数“-oracle.jdbc.J2EE13Compliant=true”
2.通过代码在项目初始化时设置System.getProperties().setProperty("oracle.jdbc.J2EE13Compliant", "true");
