### ISSUE TITLE
 'rdb:master-slave-data-source' 中不允许出现属性 'strategy-type'

### ISSUE THREAD

**Issue by tian6318** [shardingjdbc/sharding-jdbc#415]
在配置完读写分离的属性，启动的时候出现 该异常，无法解决，请问是什么愿意

Caused by: org.xml.sax.SAXParseException; lineNumber: 22; columnNumber: 32; cvc-complex-type.3.2.2: 元素 'rdb:master-slave-data-source' 中不允许出现属性 'strategy-type'。

**Comment by cocodroid** [comment]
你都没说版本号。
我这边看2.0.0.M1的只有读写分离的标签配置确实没有这个 'strategy-type'啊
<bean id="randomStrategy" class="io.shardingjdbc.core.api.algorithm.masterslave.RandomMasterSlaveLoadBalanceAlgorithm" />  
    <master-slave:data-source id="masterSlaveDataSource" master-data-source-name="demo_ds_master" slave-data-source-names="demo_ds_slave_0, demo_ds_slave_1" strategy-ref="randomStrategy" />

**Comment by cocodroid** [comment]
@tian6318 
你都没说版本号。
我这边看2.0.0.M1的只有读写分离的标签配置确实没有这个 'strategy-type'啊
<bean id="randomStrategy" class="io.shardingjdbc.core.api.algorithm.masterslave.RandomMasterSlaveLoadBalanceAlgorithm" />
    
    <master-slave:data-source id="masterSlaveDataSource" master-data-source-name="demo_ds_master" slave-data-source-names="demo_ds_slave_0, demo_ds_slave_1" strategy-ref="randomStrategy" />

**Comment by tian6318** [comment]
这边我使用的，1.5.4 版本

**Comment by terrymanu** [comment]
请核对正确的版本后再使用
