### ISSUE TITLE
强制路由到单表或单库不能翻页

### ISSUE THREAD

**Issue by wangshuguan** [shardingjdbc/sharding-jdbc#416]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.1
### Expected behavior
可以正常翻页，这里使用jpa分页
### Actual behavior
除了第一页，其它页都为空
### Steps to reproduce the behavior
强制路由到一张分片表，基本的jpa分页操作，如果读取非第一页数据，查询内容为空
### Please provide the reproduce example codes (such as github link) if possible.
如下，page
                    HintManager hintManager = HintManager.getInstance();
                    hintManager.addDatabaseShardingValue("customer", "cust_nbr", "10000104");
                    hintManager.addTableShardingValue("customer", "cust_nbr", "10000104");
                    Pageable pageable = new PageRequest(3, 20, new Sort("custNbr"));
                    Page<Customer> custs = customerRepository.findAll(getWhereClause("D"),pageable);
                    List<TxnCustomerPersonal> pageContent =  custs.getContent();

**Comment by terrymanu** [comment]
diplicate with #375
