### ISSUE TITLE
sharding-jdbc单库拆分多表的查询效率问题

### ISSUE THREAD

**Issue by 15827071127** [shardingjdbc/sharding-jdbc#418]
测试工程地址：https://github.com/15827071127/test-sharding-jdbc

1.给vst_member表插入2300万条记录

2.根据取模插入子表数据
INSERT INTO vst_member_0 SELECT * FROM vst_member WHERE vst_uid % 10 = 0
INSERT INTO vst_member_1 SELECT * FROM vst_member WHERE vst_uid % 10 = 1
...
INSERT INTO vst_member_9 SELECT * FROM vst_member WHERE vst_uid % 10 = 9

3.用navicat执行如下语句：花费9秒
SELECT * FROM vst_member WHERE vst_uid LIKE '%888888%'

4.用navicat执行如下语句：每条都花费900毫秒
SELECT * FROM vst_member_0 WHERE vst_uid LIKE '%888888%';
SELECT * FROM vst_member_1 WHERE vst_uid LIKE '%888888%';
SELECT * FROM vst_member_2 WHERE vst_uid LIKE '%888888%';
SELECT * FROM vst_member_3 WHERE vst_uid LIKE '%888888%';
SELECT * FROM vst_member_4 WHERE vst_uid LIKE '%888888%';
SELECT * FROM vst_member_5 WHERE vst_uid LIKE '%888888%';
SELECT * FROM vst_member_6 WHERE vst_uid LIKE '%888888%';
SELECT * FROM vst_member_7 WHERE vst_uid LIKE '%888888%';
SELECT * FROM vst_member_8 WHERE vst_uid LIKE '%888888%';
SELECT * FROM vst_member_9 WHERE vst_uid LIKE '%888888%';

5.使用sharding-jdbc执行如下语句：花费10秒
SELECT * FROM vst_member WHERE vst_uid LIKE '%888888%'
（我预期的是花费1秒 = 900毫秒 + 归并的时间）

6.执行PeopleAccessMemberThread2的main函数，花费2秒

测试结果：用原生的JDBC+10个线程并发查询的时间开销小于sharding-jdbc，如何提高sharding-jdbc
的效率？

**Comment by terrymanu** [comment]
由于Druid连接池不支持多线程访问，因此对于同一库上的多个分表，采用的是单线程访问。
未来会做提升，增加配置项，让使用方决定是否开启多线程。
未来修改方案：
配置是否同一库的多表采用不同的连接。true，则开启多线程，缺点是同库的多表无法保持在一个acid事务中；false则同库的多表采用一个连接，串行执行（即目前的方式）。
