### ISSUE TITLE
请问为什么我的日志输出都是正确的，看库里确没有记录

### ISSUE THREAD

**Issue by Lxpd** [shardingjdbc/sharding-jdbc#420]
看日志输出一切都正常，打印出来的sql语句也是正确， 而且也返回了20:56:33.545 [http-bio-80-exec-6] DEBUG c.j.c.a.d.C.insertSelective - <==    Updates: 1  说明都执行正确了 ，但是我看我的库里的表 一条数据都没有，，  请问谁遇到过，什么原因，  我把我分库分表的所有表都查看了，愣是一条数据也没有，还没b报任何错误???????????????

**Comment by Lxpd** [comment]
日志说成功了，确没数据   还没报任何错误   什么情况， 请问谁遇到过？？

**Comment by terrymanu** [comment]
事务问题，读写分离问题，环境看错了的问题等。请从自己的代码和环境中查找原因吧。
