### ISSUE TITLE
同一条数据出现在不同的表中

### ISSUE THREAD

**Issue by FanswGit** [shardingjdbc/sharding-jdbc#426]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.4.2
### Expected behavior
同一分表键的数据应该在一个表中
### Steps to reproduce the behavior
概率性

**Comment by terrymanu** [comment]
请描述的足够清晰，并提供可供重现的demo

**Comment by terrymanu** [comment]
由于未说明理由自行关闭问题，因此认为该问题属于无效问题。
