### ISSUE TITLE
官方qq不给进,只能在这问个问题了.

### ISSUE THREAD

**Issue by PrimaryKey3610** [shardingjdbc/sharding-jdbc#427]
@Bean
  public KeyGenerator getIdGenerator() {
    return new DefaultKeyGenerator();
  }

然后我通过注入的方式
 @Autowired
  private KeyGenerator commonSelfIdGenerator;

然后在保存实体方法中调用

  public void add() throws InterruptedException {
    for (int i = 1; i < 1000; i++) {
      Customer order = new Customer();
      long l = commonSelfIdGenerator.generateKey().longValue();
      System.out.println(l + "----" );
      order.setId(l);
      order.setName("测试" + i);
      order.setType("类型" + i);
      order.setGroupId((long) i);
      customerRepository.save(order);
    }
  }
这样保存的话,生成的主键全部都是以偶数产生的,而分表的机制就是偶数,奇数,这样就导致了所有的保存数据都在一张表中,而另外一张表是空的.   但是如果我customerRepository.save(order);这句保存注释掉,那么主键策略就偶数,奇数都会产生了. 这是个什么样的问题. 麻烦解答一下吧.

**Comment by terrymanu** [comment]
关于问题，请阅读文档：http://shardingjdbc.io/docs/01-start/faq/ 第9个问题的回答
关于入群：群中是实名制交流，您入群时未提供公司名称，拒绝您入群也明确写了拒绝理由，如有入群需求，请提供公司名称。
