### ISSUE TITLE
工程引入PropertyPlaceholderConfigurer替换变量时路由规则解析异常

### ISSUE THREAD

**Issue by YZlichengjun** [shardingjdbc/sharding-jdbc#430]
Please answer these questions before submitting your issue. Thanks!

### Expected behavior
配置文件中引入org.springframework.beans.factory.config.PropertyPlaceholderConfigurer能够正常替换变量
### Actual behavior
<sharding:table-rule logic-table="t_order" generate-key-column="order_id"
					actual-data-nodes="demo_ds.t_order_${0..1}" table-strategy-ref="orderTableShardingStrategy" />
程序启动会报${0..1}无法解析
Could not resolve placeholder '0..1' in value "demo_ds.t_order_${0..1}"

**Comment by www1350** [comment]
ignore-unresolvable="true"
