### ISSUE TITLE
关于自定义规则分库分表 in 查询的问题咨询

### ISSUE THREAD

**Issue by hongye1114** [shardingjdbc/sharding-jdbc#431]
大神好
公司原有分库规则
db0
  ├── t_order_0 
  └── t_order_1 
db1
  ├── t_order_2
  ├── t_order_3
准备再不该分库规则的情况下使用shardingjdbc
发现在使用in查询的时候有一些问题
路由在不同库中的话会找不到表
版本2.0.0.M2
```java
private Collection<String> doSharding(final Collection<String> availableTargetNames, final ListShardingValue<?> shardingValue) {
        Collection<String> result = new LinkedList<>();
        for (PreciseShardingValue<?> each : transferToPreciseShardingValues(shardingValue)) {
            result.add(preciseShardingAlgorithm.doSharding(availableTargetNames, each));
        }
        return result;
    }

```
如果是in查询 因为不同库表不一样 路由在不同库中存在找不到表的情况导致异常
是不是只要保证result.size() 大于0就行 ？
目前没有使用动态修改运行时数据源功能是不是无法试用这种分表规则

**Comment by terrymanu** [comment]
我们希望使用shading-jdbc的数据库都是水平扩展的，即每个库的数据库表结构和名称都完全一样。
如果非水平扩展，也可以通过灵活的分片策略实现，但复杂度较高，in查询不能用等，需要结合改写后的sql断定。
由于不推荐这么使用，因此这个issue我就关了
