### ISSUE TITLE
Spring boot + hibernate +oralce 启动更新数据库时出错

### ISSUE THREAD

**Issue by zhang2go** [shardingjdbc/sharding-jdbc#432]
数据库使用
在spring 中配置 spring.jpa.properties.hibernate.hbm2ddl.auto=update 时启动出错，错误信息为：
Caused by: io.shardingjdbc.core.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'UNION'.
断点调试在执行这条数据库实出错
 select sequence_name from all_sequences  union select synonym_name   from all_synonyms us, all_sequences asq  where asq.sequence_name = us.table_name    and asq.sequence_owner = us.table_owner。
大概就是hibernate如果配置oracle数据库自动更新，hibernate会使用到union语法。
求解

**Comment by zhang2go** [comment]
如果使用 node又不会自动更新数据库表生成

**Comment by terrymanu** [comment]
不支持UNION
