### ISSUE TITLE
com.dangdang.ddframe.rdb.sharding.parsing.lexer.LexerEngine.skipUntil(LexerEngine.java:162) 有没有可能导致CPU占用过高

### ISSUE THREAD

**Issue by yuexianbing** [shardingjdbc/sharding-jdbc#440]
1.5.4.1 版本在使用过程重，3个8核节点，每个节点cpu使用达到600%左右。
看了堆栈，在这个方法的耗时都比较高，每个占用cpu高的线程最后都是在这里（相对并发也较多）：com.dangdang.ddframe.rdb.sharding.parsing.lexer.LexerEngine.skipUntil，请问，这个方法会使用大量的cpu 么？

**Comment by yuexianbing** [comment]
![skipunitl](https://user-images.githubusercontent.com/31297055/32817469-ca6b5e10-c9f8-11e7-9583-1cfe13e74237.PNG)

**Comment by terrymanu** [comment]
skipUntil的代码：

,,,java

    public void skipUntil(final TokenType... tokenTypes) {
        Set<TokenType> tokenTypeSet = Sets.newHashSet(tokenTypes);
        tokenTypeSet.add(Assist.END);
        while (!tokenTypeSet.contains(lexer.getCurrentToken().getType())) {
            lexer.nextToken();
        }
    }

,,,

应该没什么特别的消耗cpu的操作

**Comment by terrymanu** [comment]
长时间未跟进反馈。
我们自己分析代码找不到什么可优化的空间了，因此此issue我关闭了
