### ISSUE TITLE
org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar时出错

### ISSUE THREAD

**Issue by suxg003** [shardingjdbc/sharding-jdbc#446]
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project sharding-jdbc-core: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - 错误: 读取/Users/wjj/.m2/repository/org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar时出错; invalid LOC header (bad signature)
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/wjj/codeGithub/sharding-jdbc/sharding-jdbc-core/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR]

**Comment by cocodroid** [comment]
@suxg003 这问题不属于sj的范畴！你可以 删除maven中的snakeyaml-1.16.jar重新编译打包吧

**Comment by terrymanu** [comment]
请自行将依赖加载正确
