### ISSUE TITLE
sharding-jdbc-spring-boot-data-mybatis-example 连接没全部释放

### ISSUE THREAD

**Issue by liuxiaozhu** [shardingjdbc/sharding-jdbc#448]
master分支，均采用默认配置。
修改 `SpringBootDataMybatisMain`
```java
DemoService service = applicationContext.getBean(DemoService.class);
service.demo();
service.demo();
```
连接没有全部释放。第二次执行 `demo()` 时连接不够用了，默认 8 个连接。
分析原因 `AbstractConnectionAdapter` 中 
```java
private final Map<String, Connection> cachedConnections = new HashMap();
```
这个 HashMap 感觉有点不太合适，例如：ds_0 可能会有两个 connection ， sqlSession close 时 cache 中只有一个，还请各位大神赐教。

**Comment by haocao** [comment]
Duplicate with #452
