### ISSUE TITLE
分库分表中是不是不支持exists关键字？

### ISSUE THREAD

**Issue by TongHaoException** [shardingjdbc/sharding-jdbc#451]
我的sql中采用exists无法解析exists中的表
select
        p.package_id
        from t_package p where  EXISTS (
        select 1
        FROM t_package_skuinfo s,t_transaction t where s.transaction_id=t.order_id and s.package_id = p.package_id);

**Comment by terrymanu** [comment]
不支持这样的子查询。详情请阅读文档

**Comment by TongHaoException** [comment]
select  * from user where user_id in (select id from order)这种是不是也不支持？
