### ISSUE TITLE
sharding-jcbc拦截了sql，重写后，出现中文乱码，中文变成 了16进制的

### ISSUE THREAD

**Issue by laiquanqiangloveyou** [shardingjdbc/sharding-jdbc#454]
版本1.5.4.1   我从头到尾打印我的中文传参，发现都是中文，就是sharding-jdbc拦截后，执行就变乱码了。
{
  "timestamp": 1511171152170,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.mybatis.spring.MyBatisSystemException",
  "message": "nested exception is org.apache.ibatis.exceptions.PersistenceException: \r\n### Error updating database.  Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\\xE4\\xB8\\xAD\\xE6\\x96\\x87' for column 'goods_name' at row 1\r\n### The error may involve com.jony.mapper.GoodsMapper.createGoods-Inline\r\n### The error occurred while setting parameters\r\n### SQL: insert into   em_goods(goods_id, goods_name,sku_id) values (?, ?, ?)\r\n### Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\\xE4\\xB8\\xAD\\xE6\\x96\\x87' for column 'goods_name' at row 1",
  "path": "/goods/createGoods"
}

**Comment by laiquanqiangloveyou** [comment]
求解决办法。我的数据库全是utf-8,java编码utf-8,

**Comment by terrymanu** [comment]
这是mybatis使用的问题，报错信息与sharding-jdbc无关，只是透传了mybatis的stack trace，因此关闭了。请查找mybatis相关的解决办法。
