### ISSUE TITLE
关于mybatis与sharding-jdbc集成使用出现中文乱码的问题

### ISSUE THREAD

**Issue by laiquanqiangloveyou** [shardingjdbc/sharding-jdbc#456]
问题一直找不到原因。为了找出原因，我写了一个没集成sharding-jdbc的demo。我使用的是springboot-1.4.3和 <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.2.0</version>
        </dependency>  做了一个demo，发现插入数据没有乱码，数据库连接jdbc:mysql://120.77.37.119:3306/emall?useUnicode=true&characterEncoding=utf8。同样的环境我集成了sharding-jdbc就出现乱码了，数据无法插入数据库。但是数据库连接方式去掉characterEncoding=utf8就可以插入数据库，这个时候由于和数据库编码格式不一致导致的乱码。请问你们谁用springboot集成过sharding-jdbc，有没有出现这种问题。

**Comment by haocao** [comment]
乱码问题应该与sharding-jdbc没有关系，请先自己检查，谢谢。
