### ISSUE TITLE
按组ID插入没问题，但查询出现问题，求助

### ISSUE THREAD

**Issue by hanfre** [shardingjdbc/sharding-jdbc#457]
**表结构：**
表test_data，字段categoryid,title,intro,createdata,userid

**分表方式**
想按照categoryid进行分表，然后下面代码也是这么写的
 @Override
    public String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Integer> shardingValue) {
       //shardingValue这个值会是categoryID，所以直接返回"表名_分类ID"
    	for (String each : availableTargetNames) {
    		return String.format("%s_%s",each,shardingValue.getValue());
    	}

        throw new UnsupportedOperationException();
    }

**以上在执行的时候没问题，但是执行插入的时候出问题了 提示不存在test_data这个表**，我的配置如下

 <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule data-source-names="shardingDataSource_0">
            <sharding:table-rules>
                <sharding:table-rule logic-table="test_data" actual-data-nodes="shardingDataSource_0.test_data_${categoryid}" table-strategy-ref="categoryId_TableShardingStrategy" generate-key-column="categoryid" />
            </sharding:table-rules>
            <sharding:binding-table-rules>
                <sharding:binding-table-rule logic-tables="test_data"/>
            </sharding:binding-table-rules>
        </sharding:sharding-rule>
    </sharding:data-source>

求助 应该怎么配置呢

**Comment by hanfre** [comment]
1、插入的时候没问题，查询就提示test_data这个表不存在。。。
2、关于test_data_${categoryid}这个表我在分类保存的时候会自动创建的。

求助

**Comment by haocao** [comment]
请先阅读文档和example理解分片的含义，如：shardingDataSource_0.test_data_${0...2}，而不是shardingDataSource_0.test_data_${categoryid}
