### ISSUE TITLE
已在spring下通过配置XML方式配置，但是对于部分已配置的参数是否支持动态修改？

### ISSUE THREAD

**Issue by hanfre** [shardingjdbc/sharding-jdbc#459]
比如配置文件已经配置切片逻辑，逻辑表等，是否可以再通过代码进行动态修改？
TableRuleConfiguration orderTableRuleConfig = new TableRuleConfiguration();
        orderTableRuleConfig.setLogicTable("表名");
     orderTableRuleConfig.setActualDataNodes("逻辑表名,逻辑表名...");

**Comment by terrymanu** [comment]
1.x 不可以
2.x的配置动态化功能可以
