### ISSUE TITLE
DDL操作，链接获取后不会自动释放归还连接池。

### ISSUE THREAD

**Issue by ljgGit** [shardingjdbc/sharding-jdbc#460]
Please answer these questions before submitting your issue. Thanks!
第一次使用 ， 求教  ：
### Which version of Sharding-Jdbc do you using?
1.5.4  1.5.4.1 ... 等 都有
### Please provide the reproduce example codes (such as github link) if possible.
使用官方提供的jdbc用例，
private static void executeUpdate(final DataSource dataSource, final String sql) throws SQLException {
        Connection conn = null;
        PreparedStatement preparedStatement = null;
        try {
            conn = dataSource.getConnection();
            preparedStatement = conn.prepareStatement(sql);
            System.out.println(sql);
            preparedStatement.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // DDL 操作不会释放   可能是分表时DDL操作  改写的问题。
            System.out.println("----------------------");
            preparedStatement.close();
            conn.close();
        }
    }

场景： 仅分表 。
DML类型的SQL  可以正常释放  归还到连接池。
DDL类型的SQL   没有正常释放。

**Comment by terrymanu** [comment]
duplicate with #452
