### ISSUE TITLE
不支持oracle的视图吗，比如user_tables，user_tab_columns

### ISSUE THREAD

**Issue by xusheng1987** [shardingjdbc/sharding-jdbc#462]
<rdb:data-source id="dataSource">
		<rdb:sharding-rule data-sources="dataSource1,dataSource2" default-data-source="dataSource1">
			<rdb:table-rules>
				<rdb:table-rule logic-table="sys_user" data-source-names="dataSource2"/>
				<rdb:table-rule logic-table="sys_role" data-source-names="dataSource2"/>
				<rdb:table-rule logic-table="sys_user_role" data-source-names="dataSource2"/>
				<rdb:table-rule logic-table="sys_role_menu" data-source-names="dataSource2"/>
				<rdb:table-rule logic-table="sys_menu" data-source-names="dataSource2"/>
				<rdb:table-rule logic-table="user_tables" data-source-names="dataSource1"/>
				<rdb:table-rule logic-table="user_tab_comments" data-source-names="dataSource1"/>
				<rdb:table-rule logic-table="user_tab_columns" data-source-names="dataSource1"/>
				<rdb:table-rule logic-table="user_col_comments" data-source-names="dataSource1"/>
				<rdb:table-rule logic-table="user_cons_columns" data-source-names="dataSource1"/>
				<rdb:table-rule logic-table="user_constraints" data-source-names="dataSource1"/>
			</rdb:table-rules>
			<rdb:default-database-strategy sharding-columns="none" algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.database.NoneDatabaseShardingAlgorithm"/>
			<rdb:default-table-strategy sharding-columns="none" algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.table.NoneTableShardingAlgorithm"/>
		</rdb:sharding-rule>
	</rdb:data-source>

只用了分库，不分表，报这个错误
错误信息：nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]' 

版本是1.5.4.1

**Comment by terrymanu** [comment]
看错误信息是没有把分库分表rule配置正确，在sql中既没找到分片需要的表，也没有default datasource，和是不是oracle视图没关系
