### ISSUE TITLE
com.dangdang.ddframe.rdb.sharding.parsing.lexer.token.Token 在虚拟机内存中有很多的实例

### ISSUE THREAD

**Issue by yuexianbing** [shardingjdbc/sharding-jdbc#464]
> 请看下，还是cpu使用过高的问题，这两天发现com.dangdang.ddframe.rdb.sharding.parsing.lexer.token.Token虚拟机不停的再处理这个类的实例，这个是sql解析用到的，这个实例的创建销毁貌似很频繁啊！
![token](https://user-images.githubusercontent.com/31297055/33160185-181bf112-d055-11e7-83ea-be936378c10c.PNG)

**Comment by terrymanu** [comment]
实例创建销毁很频繁，一个YGC也能解决。请问是否真的产生FGC，影响业务了？脱离上下文的数据并没有意义。请提供运行了多久，进行了几次FGC，几次YGC，每次间隔多少，内存的使用情况等综合指标。

**Comment by yuexianbing** [comment]
![skipuntil](https://user-images.githubusercontent.com/31297055/33358886-51aa22e0-d506-11e7-84a6-a1b55c1784aa.PNG)
![token](https://user-images.githubusercontent.com/31297055/33358888-538b7802-d506-11e7-83c2-1c932d5af01c.PNG)
![gc](https://user-images.githubusercontent.com/31297055/33358896-5db5e5c4-d506-11e7-897d-23cb7f9e02b7.PNG)
@terrymanu  您好，不好意思，前几天不在公司。这个是我今天截的部分数据，这些数据是在我禁掉生产的这个节点的前提下看到的。 禁掉节点后 3个小时了，Token还是在不停的创建销毁，线程堆栈runnable也显示在com.dangdang.ddframe.rdb.sharding.parsing.lexer.LexerEngine#skipUntil 这个方法的162行。我测试了下单线程的情况下我的这句sql是进不到 162行的。您看下呢。

**Comment by yuexianbing** [comment]
禁掉了dubbo，没有放生任何方法调用。 @terrymanu

**Comment by yuexianbing** [comment]
到目前为止，服务器还是这几个线程在狂飙cpu，是不是在com.dangdang.ddframe.rdb.sharding.parsing.lexer.LexerEngine#skipUntil出现了死循环呢
![default](https://user-images.githubusercontent.com/31297055/33360807-6868b2b2-d510-11e7-8bce-61afa3d9e9bb.PNG)

**Comment by terrymanu** [comment]
sql的char由于没有匹配单引号，并未关闭。恰好sql中的下一个char又是汉字，会导致这个问题出现。
sql示例：

```sql
UPDATE product p SET p.title='Title's',s.description='中文' WHERE p.product_id=?
```

**Comment by terrymanu** [comment]
fix at 2.0.0.M4
