### ISSUE TITLE
关于sharding-jdbc不支持OR和冗余括号的疑问？

### ISSUE THREAD

**Issue by lialatd** [shardingjdbc/sharding-jdbc#466]
您好，我最近正在研究sharding-jdbc（2.0.0.M2），这里有几个疑问想要了解一下：
（1）关于屏蔽OR（下面仅对DQL分析，其他语句尚未了解）
第一种情况：查询语句中不包含分片键
第二种情况：查询语句中包含分片键
对于第一种情况，不管查询条件中包含不包含OR，都采用全路由，所以路由上不受OR的影响
对于第二种情况再细分为（条件中包含OR但OR左右连接的条件不包含分片键）和（条件中包含OR且OR左右连接的条件包含分片键），对于前面这种情况，根据分片策略进行路由也不受OR的影响，至于后面这种情况，我想应该是当OR左右连接的条件不同时包含分片键的时候才可能会出现路由有误的情况吧？或者还存在什么其他的可能导致路由有误，如果有的话希望您能指点一下
（2）关于不支持冗余的括号
从源码上看，修改部分代码完全可以像skipIfEqual(Symbol.LEFT_PAREN)一样跳过连续的左右括号，我不是很清楚为什么不这样做呢？
前面两点仅仅是对于查询语句来问的，如果是因为DML或者DCL的原因不支持的话，希望您能抽空指点一下，谢谢了

**Comment by terrymanu** [comment]
1. OR路由并不简单，与and和各种括号中优先级，并不是全路由就能解决的。需要拆为旋转树解析才可以
2. 冗余括号是同理，需要解析为抽象语法树。目前不解析冗余括号，整个解析上下文是平层的。加上括号，and和or，需要AST。具体理论请看编译原理会好一些
