### ISSUE TITLE
2.0版本还不支持批量插入么

### ISSUE THREAD

**Issue by hanfre** [shardingjdbc/sharding-jdbc#467]
2.0版本还不支持insert into * ()values(*)(*)(*)

这种value后面的还不支持么？

**Comment by hanfre** [comment]
批量插入提示错误Caused by: java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).

**Comment by hanfre** [comment]
### SQL: INSERT INTO test(ids,version) VALUES          (?, ?)    ,     (?, ?)    ;
### Cause: io.shardingjdbc.core.exception.ShardingJdbcException: Invoke jdbc method exception

**Comment by terrymanu** [comment]
duplicate with #290
