### ISSUE TITLE
来求助了，关于批量插入的问题

### ISSUE THREAD

**Issue by hanfre** [shardingjdbc/sharding-jdbc#468]
亮哥，我也知道目前支持批量插入了，但是我执行批量插入仍然报错是为什么

### Cause: io.shardingjdbc.core.exception.ShardingJdbcException: Invoke jdbc method exception
。。。。
Caused by: java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
。。。。。

**Comment by terrymanu** [comment]
目前不支持
duplicate with #290
