### ISSUE TITLE
分页查询数据有重复，怎么回事？

### ISSUE THREAD

**Issue by sr0210** [shardingjdbc/sharding-jdbc#470]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
2.0.0.M2
### Expected behavior
不重复
### Actual behavior
数据有重复
### Steps to reproduce the behavior
带非分页键的条件分页查询
### Please provide the reproduce example codes (such as github link) if possible.
select * from table where field1 = 1

**Comment by terrymanu** [comment]
请提供数据库表结构，分片策略配置以及sql.show的相关日志

**Comment by terrymanu** [comment]
你的sql ： select * from table where field1 = 1
并未分页。由于长时间未反馈，而且这些基本测试我们都有测试用例，请随意参考。因此这个issue我关闭了。
