### ISSUE TITLE
数据库表每天自动生成，怎么在调用查询方法的时候，重新绑定数据库表？

### ISSUE THREAD

**Issue by lianghang911** [shardingjdbc/sharding-jdbc#478]
绑定数据表，生成虚拟表，怎么样多次绑定？ 数据库每小时生成一张表，怎么样多次动态绑定？
![qq 20171204103433](https://user-images.githubusercontent.com/23113019/33533868-cb2f4934-d8de-11e7-84df-a0a301525004.png)
![image](https://user-images.githubusercontent.com/23113019/33533887-e3972c3a-d8de-11e7-9925-ef6b4e7b0458.png)

**Comment by terrymanu** [comment]
使用1.x的动态表或2.x的配置动态化
