### ISSUE TITLE
关于柔性事务配置数据源

### ISSUE THREAD

**Issue by yuanfuwang** [shardingjdbc/sharding-jdbc#479]
#事务日志的数据源.
transactionLogDataSource:
  ds_trans: !!org.apache.commons.dbcp.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trans_log
    username: root
    password:

请问这里的事务库trans_log中包含哪些表？有下载的地方吗？

**Comment by terrymanu** [comment]
自己建一个trans_log的schema即可，表结构会自动创建好
