### ISSUE TITLE
使用select  from in (,id,,,) 语句时，非常耗时，id 是分片字段

### ISSUE THREAD

**Issue by winworm** [shardingjdbc/sharding-jdbc#483]
Please answer these questions before submitting your issue. Thanks!

**Comment by terrymanu** [comment]
请问原始sql是否就很耗时，这个和sharding-jdbc这一层面有关系么？

**Comment by terrymanu** [comment]
长时间无反馈，信息不足，该issue关闭

**Comment by winworm** [comment]
非常抱歉，刚刚才看到消息，原始sql大概50ms左右， 慢的原因可能是我分了10个库，100个表， 我的sql中in 列表大小为10.   当使用shardjdbc 连接时，会根据不同的分片id决定不同的库（最大可能分散到10个库中），和不同的表，这样就会有交叉执行100条sql ，然后时间变得很慢，这个是大概分析的原因，不知道是否是这样的。
