### ISSUE TITLE
table配置中actualDataNode 长度过长时导致解析过慢

### ISSUE THREAD

**Issue by luciferganwei** [shardingjdbc/sharding-jdbc#484]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
2.0.0.M3
### Expected behavior
正常快速启动
### Actual behavior
启动卡在 TableRuleConfiguration.java   的第64 行:
new InlineExpressionParser(this.actualDataNode).evaludate();

### Steps to reproduce the behavior
因为我们的数据分片的格式很奇怪，无法通过inline表达式直接生成（历史遗留问题），所以我们自己通过一个类生成了每一个数据分片，总共1024 个数据分片，都是按照官方文档中使用格式逗号隔开的字符串。

然后就正常启动，然后发现如果只配置一个logic表的时候，好像还行。
但是如果配置了很多个logic table 后，就感觉卡住了，然后debug 后发现是上面那里的解析占据了时间。
最终分片还是能解析正确，只是中间耗时惊人。

**Comment by terrymanu** [comment]
请提供inine表达式供我们调试

**Comment by terrymanu** [comment]
另外，1024个数据分片是否有必要，请问是什么级别的业务？

**Comment by luciferganwei** [comment]
user000.t_user0000, user000.t_user0001, user000.t_user0002, user000.t_user0003, user000.t_user0004, user000.t_user0005, user000.t_user0006, user000.t_user0007, user000.t_user0008, user000.t_user0009, user000.t_user0010, user000.t_user0011, user000.t_user0012, user000.t_user0013, user000.t_user0014, user000.t_user0015, user000.t_user0016, user000.t_user0017, user000.t_user0018, user000.t_user0019, user000.t_user0020, user000.t_user0021, user000.t_user0022, user000.t_user0023, user000.t_user0024, user000.t_user0025, user000.t_user0026, user000.t_user0027, user000.t_user0028, user000.t_user0029, user000.t_user0030, user000.t_user0031, user000.t_user0032, user000.t_user0033, user000.t_user0034, user000.t_user0035, user000.t_user0036, user000.t_user0037, user000.t_user0038, user000.t_user0039, user000.t_user0040, user000.t_user0041, user000.t_user0042, user000.t_user0043, user000.t_user0044, user000.t_user0045, user000.t_user0046, user000.t_user0047, user000.t_user0048, user000.t_user0049, user000.t_user0050, user000.t_user0051, user000.t_user0052, user000.t_user0053, user000.t_user0054, user000.t_user0055, user000.t_user0056, user000.t_user0057, user000.t_user0058, user000.t_user0059, user000.t_user0060, user000.t_user0061, user000.t_user0062, user000.t_user0063, user001.t_user0064, user001.t_user0065, user001.t_user0066, user001.t_user0067, user001.t_user0068, user001.t_user0069, user001.t_user0070, user001.t_user0071, user001.t_user0072, user001.t_user0073, user001.t_user0074, user001.t_user0075, user001.t_user0076, user001.t_user0077, user001.t_user0078, user001.t_user0079, user001.t_user0080, user001.t_user0081, user001.t_user0082, user001.t_user0083, user001.t_user0084, user001.t_user0085, user001.t_user0086, user001.t_user0087, user001.t_user0088, user001.t_user0089, user001.t_user0090, user001.t_user0091, user001.t_user0092, user001.t_user0093, user001.t_user0094, user001.t_user0095, user001.t_user0096, user001.t_user0097, user001.t_user0098, user001.t_user0099, user001.t_user0100, user001.t_user0101, user001.t_user0102, user001.t_user0103, user001.t_user0104, user001.t_user0105, user001.t_user0106, user001.t_user0107, user001.t_user0108, user001.t_user0109, user001.t_user0110, user001.t_user0111, user001.t_user0112, user001.t_user0113, user001.t_user0114, user001.t_user0115, user001.t_user0116, user001.t_user0117, user001.t_user0118, user001.t_user0119, user001.t_user0120, user001.t_user0121, user001.t_user0122, user001.t_user0123, user001.t_user0124, user001.t_user0125, user001.t_user0126, user001.t_user0127, user002.t_user0128, user002.t_user0129, user002.t_user0130, user002.t_user0131, user002.t_user0132, user002.t_user0133, user002.t_user0134, user002.t_user0135, user002.t_user0136, user002.t_user0137, user002.t_user0138, user002.t_user0139, user002.t_user0140, user002.t_user0141, user002.t_user0142, user002.t_user0143, user002.t_user0144, user002.t_user0145, user002.t_user0146, user002.t_user0147, user002.t_user0148, user002.t_user0149, user002.t_user0150, user002.t_user0151, user002.t_user0152, user002.t_user0153, user002.t_user0154, user002.t_user0155, user002.t_user0156, user002.t_user0157, user002.t_user0158, user002.t_user0159, user002.t_user0160, user002.t_user0161, user002.t_user0162, user002.t_user0163, user002.t_user0164, user002.t_user0165, user002.t_user0166, user002.t_user0167, user002.t_user0168, user002.t_user0169, user002.t_user0170, user002.t_user0171, user002.t_user0172, user002.t_user0173, user002.t_user0174, user002.t_user0175, user002.t_user0176, user002.t_user0177, user002.t_user0178, user002.t_user0179, user002.t_user0180, user002.t_user0181, user002.t_user0182, user002.t_user0183, user002.t_user0184, user002.t_user0185, user002.t_user0186, user002.t_user0187, user002.t_user0188, user002.t_user0189, user002.t_user0190, user002.t_user0191, user003.t_user0192, user003.t_user0193, user003.t_user0194, user003.t_user0195, user003.t_user0196, user003.t_user0197, user003.t_user0198, user003.t_user0199, user003.t_user0200, user003.t_user0201, user003.t_user0202, user003.t_user0203, user003.t_user0204, user003.t_user0205, user003.t_user0206, user003.t_user0207, user003.t_user0208, user003.t_user0209, user003.t_user0210, user003.t_user0211, user003.t_user0212, user003.t_user0213, user003.t_user0214, user003.t_user0215, user003.t_user0216, user003.t_user0217, user003.t_user0218, user003.t_user0219, user003.t_user0220, user003.t_user0221, user003.t_user0222, user003.t_user0223, user003.t_user0224, user003.t_user0225, user003.t_user0226, user003.t_user0227, user003.t_user0228, user003.t_user0229, user003.t_user0230, user003.t_user0231, user003.t_user0232, user003.t_user0233, user003.t_user0234, user003.t_user0235, user003.t_user0236, user003.t_user0237, user003.t_user0238, user003.t_user0239, user003.t_user0240, user003.t_user0241, user003.t_user0242, user003.t_user0243, user003.t_user0244, user003.t_user0245, user003.t_user0246, user003.t_user0247, user003.t_user0248, user003.t_user0249, user003.t_user0250, user003.t_user0251, user003.t_user0252, user003.t_user0253, user003.t_user0254, user003.t_user0255, user004.t_user0256, user004.t_user0257, user004.t_user0258, user004.t_user0259, user004.t_user0260, user004.t_user0261, user004.t_user0262, user004.t_user0263, user004.t_user0264, user004.t_user0265, user004.t_user0266, user004.t_user0267, user004.t_user0268, user004.t_user0269, user004.t_user0270, user004.t_user0271, user004.t_user0272, user004.t_user0273, user004.t_user0274, user004.t_user0275, user004.t_user0276, user004.t_user0277, user004.t_user0278, user004.t_user0279, user004.t_user0280, user004.t_user0281, user004.t_user0282, user004.t_user0283, user004.t_user0284, user004.t_user0285, user004.t_user0286, user004.t_user0287, user004.t_user0288, user004.t_user0289, user004.t_user0290, user004.t_user0291, user004.t_user0292, user004.t_user0293, user004.t_user0294, user004.t_user0295, user004.t_user0296, user004.t_user0297, user004.t_user0298, user004.t_user0299, user004.t_user0300, user004.t_user0301, user004.t_user0302, user004.t_user0303, user004.t_user0304, user004.t_user0305, user004.t_user0306, user004.t_user0307, user004.t_user0308, user004.t_user0309, user004.t_user0310, user004.t_user0311, user004.t_user0312, user004.t_user0313, user004.t_user0314, user004.t_user0315, user004.t_user0316, user004.t_user0317, user004.t_user0318, user004.t_user0319, user005.t_user0320, user005.t_user0321, user005.t_user0322, user005.t_user0323, user005.t_user0324, user005.t_user0325, user005.t_user0326, user005.t_user0327, user005.t_user0328, user005.t_user0329, user005.t_user0330, user005.t_user0331, user005.t_user0332, user005.t_user0333, user005.t_user0334, user005.t_user0335, user005.t_user0336, user005.t_user0337, user005.t_user0338, user005.t_user0339, user005.t_user0340, user005.t_user0341, user005.t_user0342, user005.t_user0343, user005.t_user0344, user005.t_user0345, user005.t_user0346, user005.t_user0347, user005.t_user0348, user005.t_user0349, user005.t_user0350, user005.t_user0351, user005.t_user0352, user005.t_user0353, user005.t_user0354, user005.t_user0355, user005.t_user0356, user005.t_user0357, user005.t_user0358, user005.t_user0359, user005.t_user0360, user005.t_user0361, user005.t_user0362, user005.t_user0363, user005.t_user0364, user005.t_user0365, user005.t_user0366, user005.t_user0367, user005.t_user0368, user005.t_user0369, user005.t_user0370, user005.t_user0371, user005.t_user0372, user005.t_user0373, user005.t_user0374, user005.t_user0375, user005.t_user0376, user005.t_user0377, user005.t_user0378, user005.t_user0379, user005.t_user0380, user005.t_user0381, user005.t_user0382, user005.t_user0383, user006.t_user0384, user006.t_user0385, user006.t_user0386, user006.t_user0387, user006.t_user0388, user006.t_user0389, user006.t_user0390, user006.t_user0391, user006.t_user0392, user006.t_user0393, user006.t_user0394, user006.t_user0395, user006.t_user0396, user006.t_user0397, user006.t_user0398, user006.t_user0399, user006.t_user0400, user006.t_user0401, user006.t_user0402, user006.t_user0403, user006.t_user0404, user006.t_user0405, user006.t_user0406, user006.t_user0407, user006.t_user0408, user006.t_user0409, user006.t_user0410, user006.t_user0411, user006.t_user0412, user006.t_user0413, user006.t_user0414, user006.t_user0415, user006.t_user0416, user006.t_user0417, user006.t_user0418, user006.t_user0419, user006.t_user0420, user006.t_user0421, user006.t_user0422, user006.t_user0423, user006.t_user0424, user006.t_user0425, user006.t_user0426, user006.t_user0427, user006.t_user0428, user006.t_user0429, user006.t_user0430, user006.t_user0431, user006.t_user0432, user006.t_user0433, user006.t_user0434, user006.t_user0435, user006.t_user0436, user006.t_user0437, user006.t_user0438, user006.t_user0439, user006.t_user0440, user006.t_user0441, user006.t_user0442, user006.t_user0443, user006.t_user0444, user006.t_user0445, user006.t_user0446, user006.t_user0447, user007.t_user0448, user007.t_user0449, user007.t_user0450, user007.t_user0451, user007.t_user0452, user007.t_user0453, user007.t_user0454, user007.t_user0455, user007.t_user0456, user007.t_user0457, user007.t_user0458, user007.t_user0459, user007.t_user0460, user007.t_user0461, user007.t_user0462, user007.t_user0463, user007.t_user0464, user007.t_user0465, user007.t_user0466, user007.t_user0467, user007.t_user0468, user007.t_user0469, user007.t_user0470, user007.t_user0471, user007.t_user0472, user007.t_user0473, user007.t_user0474, user007.t_user0475, user007.t_user0476, user007.t_user0477, user007.t_user0478, user007.t_user0479, user007.t_user0480, user007.t_user0481, user007.t_user0482, user007.t_user0483, user007.t_user0484, user007.t_user0485, user007.t_user0486, user007.t_user0487, user007.t_user0488, user007.t_user0489, user007.t_user0490, user007.t_user0491, user007.t_user0492, user007.t_user0493, user007.t_user0494, user007.t_user0495, user007.t_user0496, user007.t_user0497, user007.t_user0498, user007.t_user0499, user007.t_user0500, user007.t_user0501, user007.t_user0502, user007.t_user0503, user007.t_user0504, user007.t_user0505, user007.t_user0506, user007.t_user0507, user007.t_user0508, user007.t_user0509, user007.t_user0510, user007.t_user0511, user008.t_user0512, user008.t_user0513, user008.t_user0514, user008.t_user0515, user008.t_user0516, user008.t_user0517, user008.t_user0518, user008.t_user0519, user008.t_user0520, user008.t_user0521, user008.t_user0522, user008.t_user0523, user008.t_user0524, user008.t_user0525, user008.t_user0526, user008.t_user0527, user008.t_user0528, user008.t_user0529, user008.t_user0530, user008.t_user0531, user008.t_user0532, user008.t_user0533, user008.t_user0534, user008.t_user0535, user008.t_user0536, user008.t_user0537, user008.t_user0538, user008.t_user0539, user008.t_user0540, user008.t_user0541, user008.t_user0542, user008.t_user0543, user008.t_user0544, user008.t_user0545, user008.t_user0546, user008.t_user0547, user008.t_user0548, user008.t_user0549, user008.t_user0550, user008.t_user0551, user008.t_user0552, user008.t_user0553, user008.t_user0554, user008.t_user0555, user008.t_user0556, user008.t_user0557, user008.t_user0558, user008.t_user0559, user008.t_user0560, user008.t_user0561, user008.t_user0562, user008.t_user0563, user008.t_user0564, user008.t_user0565, user008.t_user0566, user008.t_user0567, user008.t_user0568, user008.t_user0569, user008.t_user0570, user008.t_user0571, user008.t_user0572, user008.t_user0573, user008.t_user0574, user008.t_user0575, user009.t_user0576, user009.t_user0577, user009.t_user0578, user009.t_user0579, user009.t_user0580, user009.t_user0581, user009.t_user0582, user009.t_user0583, user009.t_user0584, user009.t_user0585, user009.t_user0586, user009.t_user0587, user009.t_user0588, user009.t_user0589, user009.t_user0590, user009.t_user0591, user009.t_user0592, user009.t_user0593, user009.t_user0594, user009.t_user0595, user009.t_user0596, user009.t_user0597, user009.t_user0598, user009.t_user0599, user009.t_user0600, user009.t_user0601, user009.t_user0602, user009.t_user0603, user009.t_user0604, user009.t_user0605, user009.t_user0606, user009.t_user0607, user009.t_user0608, user009.t_user0609, user009.t_user0610, user009.t_user0611, user009.t_user0612, user009.t_user0613, user009.t_user0614, user009.t_user0615, user009.t_user0616, user009.t_user0617, user009.t_user0618, user009.t_user0619, user009.t_user0620, user009.t_user0621, user009.t_user0622, user009.t_user0623, user009.t_user0624, user009.t_user0625, user009.t_user0626, user009.t_user0627, user009.t_user0628, user009.t_user0629, user009.t_user0630, user009.t_user0631, user009.t_user0632, user009.t_user0633, user009.t_user0634, user009.t_user0635, user009.t_user0636, user009.t_user0637, user009.t_user0638, user009.t_user0639, user010.t_user0640, user010.t_user0641, user010.t_user0642, user010.t_user0643, user010.t_user0644, user010.t_user0645, user010.t_user0646, user010.t_user0647, user010.t_user0648, user010.t_user0649, user010.t_user0650, user010.t_user0651, user010.t_user0652, user010.t_user0653, user010.t_user0654, user010.t_user0655, user010.t_user0656, user010.t_user0657, user010.t_user0658, user010.t_user0659, user010.t_user0660, user010.t_user0661, user010.t_user0662, user010.t_user0663, user010.t_user0664, user010.t_user0665, user010.t_user0666, user010.t_user0667, user010.t_user0668, user010.t_user0669, user010.t_user0670, user010.t_user0671, user010.t_user0672, user010.t_user0673, user010.t_user0674, user010.t_user0675, user010.t_user0676, user010.t_user0677, user010.t_user0678, user010.t_user0679, user010.t_user0680, user010.t_user0681, user010.t_user0682, user010.t_user0683, user010.t_user0684, user010.t_user0685, user010.t_user0686, user010.t_user0687, user010.t_user0688, user010.t_user0689, user010.t_user0690, user010.t_user0691, user010.t_user0692, user010.t_user0693, user010.t_user0694, user010.t_user0695, user010.t_user0696, user010.t_user0697, user010.t_user0698, user010.t_user0699, user010.t_user0700, user010.t_user0701, user010.t_user0702, user010.t_user0703, user011.t_user0704, user011.t_user0705, user011.t_user0706, user011.t_user0707, user011.t_user0708, user011.t_user0709, user011.t_user0710, user011.t_user0711, user011.t_user0712, user011.t_user0713, user011.t_user0714, user011.t_user0715, user011.t_user0716, user011.t_user0717, user011.t_user0718, user011.t_user0719, user011.t_user0720, user011.t_user0721, user011.t_user0722, user011.t_user0723, user011.t_user0724, user011.t_user0725, user011.t_user0726, user011.t_user0727, user011.t_user0728, user011.t_user0729, user011.t_user0730, user011.t_user0731, user011.t_user0732, user011.t_user0733, user011.t_user0734, user011.t_user0735, user011.t_user0736, user011.t_user0737, user011.t_user0738, user011.t_user0739, user011.t_user0740, user011.t_user0741, user011.t_user0742, user011.t_user0743, user011.t_user0744, user011.t_user0745, user011.t_user0746, user011.t_user0747, user011.t_user0748, user011.t_user0749, user011.t_user0750, user011.t_user0751, user011.t_user0752, user011.t_user0753, user011.t_user0754, user011.t_user0755, user011.t_user0756, user011.t_user0757, user011.t_user0758, user011.t_user0759, user011.t_user0760, user011.t_user0761, user011.t_user0762, user011.t_user0763, user011.t_user0764, user011.t_user0765, user011.t_user0766, user011.t_user0767, user012.t_user0768, user012.t_user0769, user012.t_user0770, user012.t_user0771, user012.t_user0772, user012.t_user0773, user012.t_user0774, user012.t_user0775, user012.t_user0776, user012.t_user0777, user012.t_user0778, user012.t_user0779, user012.t_user0780, user012.t_user0781, user012.t_user0782, user012.t_user0783, user012.t_user0784, user012.t_user0785, user012.t_user0786, user012.t_user0787, user012.t_user0788, user012.t_user0789, user012.t_user0790, user012.t_user0791, user012.t_user0792, user012.t_user0793, user012.t_user0794, user012.t_user0795, user012.t_user0796, user012.t_user0797, user012.t_user0798, user012.t_user0799, user012.t_user0800, user012.t_user0801, user012.t_user0802, user012.t_user0803, user012.t_user0804, user012.t_user0805, user012.t_user0806, user012.t_user0807, user012.t_user0808, user012.t_user0809, user012.t_user0810, user012.t_user0811, user012.t_user0812, user012.t_user0813, user012.t_user0814, user012.t_user0815, user012.t_user0816, user012.t_user0817, user012.t_user0818, user012.t_user0819, user012.t_user0820, user012.t_user0821, user012.t_user0822, user012.t_user0823, user012.t_user0824, user012.t_user0825, user012.t_user0826, user012.t_user0827, user012.t_user0828, user012.t_user0829, user012.t_user0830, user012.t_user0831, user013.t_user0832, user013.t_user0833, user013.t_user0834, user013.t_user0835, user013.t_user0836, user013.t_user0837, user013.t_user0838, user013.t_user0839, user013.t_user0840, user013.t_user0841, user013.t_user0842, user013.t_user0843, user013.t_user0844, user013.t_user0845, user013.t_user0846, user013.t_user0847, user013.t_user0848, user013.t_user0849, user013.t_user0850, user013.t_user0851, user013.t_user0852, user013.t_user0853, user013.t_user0854, user013.t_user0855, user013.t_user0856, user013.t_user0857, user013.t_user0858, user013.t_user0859, user013.t_user0860, user013.t_user0861, user013.t_user0862, user013.t_user0863, user013.t_user0864, user013.t_user0865, user013.t_user0866, user013.t_user0867, user013.t_user0868, user013.t_user0869, user013.t_user0870, user013.t_user0871, user013.t_user0872, user013.t_user0873, user013.t_user0874, user013.t_user0875, user013.t_user0876, user013.t_user0877, user013.t_user0878, user013.t_user0879, user013.t_user0880, user013.t_user0881, user013.t_user0882, user013.t_user0883, user013.t_user0884, user013.t_user0885, user013.t_user0886, user013.t_user0887, user013.t_user0888, user013.t_user0889, user013.t_user0890, user013.t_user0891, user013.t_user0892, user013.t_user0893, user013.t_user0894, user013.t_user0895, user014.t_user0896, user014.t_user0897, user014.t_user0898, user014.t_user0899, user014.t_user0900, user014.t_user0901, user014.t_user0902, user014.t_user0903, user014.t_user0904, user014.t_user0905, user014.t_user0906, user014.t_user0907, user014.t_user0908, user014.t_user0909, user014.t_user0910, user014.t_user0911, user014.t_user0912, user014.t_user0913, user014.t_user0914, user014.t_user0915, user014.t_user0916, user014.t_user0917, user014.t_user0918, user014.t_user0919, user014.t_user0920, user014.t_user0921, user014.t_user0922, user014.t_user0923, user014.t_user0924, user014.t_user0925, user014.t_user0926, user014.t_user0927, user014.t_user0928, user014.t_user0929, user014.t_user0930, user014.t_user0931, user014.t_user0932, user014.t_user0933, user014.t_user0934, user014.t_user0935, user014.t_user0936, user014.t_user0937, user014.t_user0938, user014.t_user0939, user014.t_user0940, user014.t_user0941, user014.t_user0942, user014.t_user0943, user014.t_user0944, user014.t_user0945, user014.t_user0946, user014.t_user0947, user014.t_user0948, user014.t_user0949, user014.t_user0950, user014.t_user0951, user014.t_user0952, user014.t_user0953, user014.t_user0954, user014.t_user0955, user014.t_user0956, user014.t_user0957, user014.t_user0958, user014.t_user0959, user015.t_user0960, user015.t_user0961, user015.t_user0962, user015.t_user0963, user015.t_user0964, user015.t_user0965, user015.t_user0966, user015.t_user0967, user015.t_user0968, user015.t_user0969, user015.t_user0970, user015.t_user0971, user015.t_user0972, user015.t_user0973, user015.t_user0974, user015.t_user0975, user015.t_user0976, user015.t_user0977, user015.t_user0978, user015.t_user0979, user015.t_user0980, user015.t_user0981, user015.t_user0982, user015.t_user0983, user015.t_user0984, user015.t_user0985, user015.t_user0986, user015.t_user0987, user015.t_user0988, user015.t_user0989, user015.t_user0990, user015.t_user0991, user015.t_user0992, user015.t_user0993, user015.t_user0994, user015.t_user0995, user015.t_user0996, user015.t_user0997, user015.t_user0998, user015.t_user0999, user015.t_user1000, user015.t_user1001, user015.t_user1002, user015.t_user1003, user015.t_user1004, user015.t_user1005, user015.t_user1006, user015.t_user1007, user015.t_user1008, user015.t_user1009, user015.t_user1010, user015.t_user1011, user015.t_user1012, user015.t_user1013, user015.t_user1014, user015.t_user1015, user015.t_user1016, user015.t_user1017, user015.t_user1018, user015.t_user1019, user015.t_user1020, user015.t_user1021, user015.t_user1022, user015.t_user1023

**Comment by terrymanu** [comment]
请问为什么要分这么多库？

**Comment by luciferganwei** [comment]
其实是根据uid ，表名是uid%1024  ,库名是 (uid%1024)/64  ，但是每个库只放64个表，比如 0库是0-63表，1库是64-127 表，需要库是三位，表是四位长度，我现在在看能不能通过groovy表达式描述

**Comment by terrymanu** [comment]
确实我们没有试过这么长的inline表达式，但是inine表达式的初始化是一次性的，时间稍微长一点也还可以接收。现在的耗时是多久？

**Comment by luciferganwei** [comment]
16 库，每库64表， 目前数据量在4千万这样，主要是历史包袱，拿到就这么分。以前是tddl组件，后来太麻烦了，就转向sharding-jdbc

**Comment by luciferganwei** [comment]
我刚才配置了22个 logic table，同样的规则，用了2分钟才解析完

**Comment by terrymanu** [comment]
我尝试优化下吧，如果是groovy解析长字符串本来就慢，我就暂时没办法了。我先看看在说

**Comment by luciferganwei** [comment]
好奇怪，我拿到macos下面解析贼快，能否在InlineExpressionParser.java   中61行中加入：if(!each.contains("{")){
        result.add(each);
        continue;
}
兼容这种没有任何表达式子的数据分片

**Comment by haocao** [comment]
经测试解析时间正常
InlineExpressionParserTest
@Test
    public void assertEvaluateForLong() {
        StringBuilder expression = new StringBuilder();
        for (int i=0; i<1024; i++) {
            expression.append("ds_" + i/64 + "" + "." + "t_user_" + i + ",");
        }
        Long begin = System.currentTimeMillis();
        List<String> expected = new InlineExpressionParser(expression.toString()).evaluate();
        Long end = System.currentTimeMillis();
        System.out.println("Evaluate method exhausted " + (end - begin) + "ms");
        assertThat(expected.size(), is(1024));
        assertThat(expected, hasItems("ds_0.t_user_0", "ds_15.t_user_1023"));
    }

输出结果
Evaluate method exhausted 3253ms

**Comment by luciferganwei** [comment]
一个logic表还是可以接受的，如果是多个表，比如20个，就很明显了

**Comment by evenardo** [comment]
https://github.com/apache/incubator-shardingsphere/pull/2522

我尝试用这种办法解决了这个问题, 请老板查收.
