### ISSUE TITLE
支持达梦数据库么

### ISSUE THREAD

**Issue by qdhk** [shardingjdbc/sharding-jdbc#486]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.3

Error creating bean with name 'myDataSource': Invocation of init method failed; nested exception is java.lang.UnsupportedOperationException: Can not support database type [DM DBMS].

**Comment by terrymanu** [comment]
抱歉，恕我孤陋寡闻，之前没听说过这个数据库。我想应该是不支持的吧。

**Comment by qdhk** [comment]
建表时如果采用分区，是否能达到跟使用此插件一样的效果

**Comment by cocodroid** [comment]
...

**Comment by whiteRabbit-me** [comment]
> 我孤陋寡闻，之前没听说过这个数据库。我

请问你怎么解决的

**Comment by agoodcoolman** [comment]
Now 2025/11/10 , is DM database Supported?
