### ISSUE TITLE
大量使用类似col >= aaa and col <= bbb的范围查询如何处理？

### ISSUE THREAD

**Issue by sptj1234** [shardingjdbc/sharding-jdbc#487]
我们的系统中有大量使用类似col >= aaa and col <= bbb的查询条件。
我们看sharding-jdbc好像只支持between and语法的范围查询。
如果改成between and对于我们系统来说需要大量修改。
如果想保持原sql不变，请问有什么解决方法么？

**Comment by terrymanu** [comment]
目前仅支持 =，in 和between。我们不认为以仅大于或仅小于作为分片键的运算符适合需要分库分表的SQL。因此暂时不打算考虑
