### ISSUE TITLE
ResultSet.getStatement与Statement.getConnection

### ISSUE THREAD

**Issue by chidaodezhongsheng** [shardingjdbc/sharding-jdbc#491]
2.0.0版本中，ResultSet反向持有的Statement和Statement反向持有的Connection无法正常close关掉。
源码如下：
AbstractResultSetAdapter中
public final Statement getStatement() throws SQLException {
        return getResultSets().get(0).getStatement();
}
ShardingStatement中connection的getter方法

**Comment by terrymanu** [comment]
fixed at 2.0.1
