### ISSUE TITLE
如何实现带分表键的or查询

### ISSUE THREAD

**Issue by Springs-wu** [shardingjdbc/sharding-jdbc#492]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.0
### Expected behavior
支持带分表键的or查询
### Actual behavior
com.dangdang.ddframe.rdb.sharding.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'OR'.
### Steps to reproduce the behavior
举例：
SELECT id FROM student WHERE root_id = 123 AND (customer_manager_id = 2 OR  designer_id = 2)
1.root_id是分表键，但不是主键。根据规则路由到某张表后最终sql应该如下：
SELECT id FROM student_1 WHERE root_id = 123 AND (customer_manager_id = 2 OR  designer_id = 2)
这样在一张表里面的sql也不支持么？

**Comment by terrymanu** [comment]
目前不支持，更多信息请阅读文档

**Comment by terrymanu** [comment]
请阅读faq：http://shardingjdbc.io/docs/01-start/faq/
第6个问题
