### ISSUE TITLE
项目引入sharding-jdbc中间件指定表分表对其他表业务的影响

### ISSUE THREAD

**Issue by bubbledoc** [shardingjdbc/sharding-jdbc#493]
### 问题：将sharding-jdbc引入整个项目，比如我只想对表 A.B.C3个表单独进行分表，所有表的DDL SQL操作都会收到影响，没法隔离A.B.C3个表之外的表不使用Sharding-Jdbc的功能。

这种场景是如何解决，我不一定需要所有业务表都进行分表，只想指定表分表。

是否要将分表业务作为独立项目拆分？

感谢阅读，给予建议参考，多谢！

**Comment by terrymanu** [comment]
请阅读faq：http://shardingjdbc.io/docs/01-start/faq/
第8个问题
