### ISSUE TITLE
新增OR语句的支持

### ISSUE THREAD

**Issue by wangqisen** [shardingjdbc/sharding-jdbc#501]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.0
### Expected behavior
期望支持OR语句
### Actual behavior
不支持OR语句

**Comment by wangqisen** [comment]
正在完成新增OR语句的工作，deadline：2018/01/30

**Comment by terrymanu** [comment]
👍 关注中

**Comment by haocao** [comment]
感谢为sharding-jdbc提供代码，以下是我们这边测试的结果：
对于SQL：
```sql
SELECT * FROM t_order WHERE user_id = ？ OR order_id = ？
```
user_id是`10`，order_id是`1000`，生成结果为：
```log
[INFO ] 13:14:39.831 [main] Sharding-JDBC-SQL - Logic SQL: SELECT * FROM t_order WHERE user_id = ? OR order_id = ?
[INFO ] 13:14:39.834 [main] Sharding-JDBC-SQL - Actual SQL: dataSource_tbl ::: SELECT * FROM t_order_0 WHERE user_id = ? OR order_id = ? ::: [10, 1000]
```
我们预期的结果应该是对多个分表查询，而目前仅对t_order_0表进行了查询，这块逻辑有点儿问题，还需要再完善一下。

**Comment by wangqisen** [comment]
@haocao 谢谢测试和review！我刚重新跑了下单测OrShardingPreparedStatementTest中的assertExecuteQueryWithParameter()测试用例，发现可以对于SQL：
SELECT * FROM t_order WHERE user_id = ？ OR order_id = ？
进行全部分表的查询。

结果如下：
[INFO ] 12:01:37.932 [main] Sharding-JDBC-SQL - Logic SQL: SELECT * FROM t_order WHERE user_id= ? OR order_id = ?
[INFO ] 12:01:37.950 [main] Sharding-JDBC-SQL - Actual SQL: dataSource_jdbc_1 ::: SELECT * FROM t_order_0 WHERE user_id= ? OR order_id = ? ::: [10, 1000]
[INFO ] 12:01:37.950 [main] Sharding-JDBC-SQL - Actual SQL: dataSource_jdbc_1 ::: SELECT * FROM t_order_1 WHERE user_id= ? OR order_id = ? ::: [10, 1000]
[INFO ] 12:01:37.950 [main] Sharding-JDBC-SQL - Actual SQL: dataSource_jdbc_0 ::: SELECT * FROM t_order_0 WHERE user_id= ? OR order_id = ? ::: [10, 1000]
[INFO ] 12:01:37.950 [main] Sharding-JDBC-SQL - Actual SQL: dataSource_jdbc_0 ::: SELECT * FROM t_order_1 WHERE user_id= ? OR order_id = ? ::: [10, 1000]

能麻烦告诉我，不能多表查询的情况是什么配置吗？

**Comment by haocao** [comment]
用仅分表的配置就可以复现，我写了测试用例放到你的分支上了，请查看。

**Comment by lxhuang0903** [comment]
问下现在支持or了吗 @wangqisen

**Comment by terrymanu** [comment]
fixed at 2.1.0

**Comment by Springs-wu** [comment]
现在支持了吗
