### ISSUE TITLE
采用分库分表后,多表关联查询怎么实现分页查询

### ISSUE THREAD

**Issue by TongHaoException** [shardingjdbc/sharding-jdbc#502]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5版本的中间件。现在有t_package表，t_transaction表，t_package_skuinfo表，t_package表与t_transaction的关系表是t_package_skuinfo表，现在根据t_package及t_transaction表的查询条件，怎么分页查询t_package表的记录数据。参考sql:
select p.package_id from t_package inner join t_package_skuinfo s on p.package_id =s.package_id inner join
t_transaction t on t.transaction_id=s.transaction_id where .......由于package表与package_skuinfo是一对多的关系。 这样查询会出现数据重复的问题

**Comment by terrymanu** [comment]
这个是sql本身的问题吧，不使用sharding jdbc也会出现数据重复？

**Comment by TongHaoException** [comment]
对的。但是sharding不支持exists关键字，所以想请教下，对于这种情况，有没有好的解决方式。

**Comment by terrymanu** [comment]
这个可能暂时没办法
是否可以看看梳理sql的可能性，在需要分库分表这样数量级的db中使用3个关联查询，应该也是互联网公司禁止的范畴。

**Comment by TongHaoException** [comment]
@terrymanu 好的，谢谢

**Comment by hongshunanhai** [comment]
如果关联查询出现1对多的情况，使用mybatis的collection方式进行分页查询（一页10条），会出现一次查询不够10条情况怎么解决？

**Comment by hwshea** [comment]
如果关联查询出现1对多的情况，使用mybatis的collection方式进行分页查询（一页10条），会出现一次查询不够10条情况怎么解决？
