### ISSUE TITLE
两表关联查询关联字段为分片键的时候，无法定位到确定的表

### ISSUE THREAD

**Issue by TongHaoException** [shardingjdbc/sharding-jdbc#503]
比如sql：select p.* from t_package inner join t_package_sku_info s on s.package_id=p.package_id
package、package_skuinfo表的表分片键都为package_id，分片策略一致。比如package、package_skuinfo表都有10张，应该是package_0--->package_skuinfo_0这种对应关系,也就是只执行10条sql。但是现在是所有的情况的都会执行一遍，也就是100条sql.

**Comment by terrymanu** [comment]
配置binding table即可
