### ISSUE TITLE
ParsingSQLRouter.processGeneratedKey方法mybatis 无法使用分布式主键空指针异常

### ISSUE THREAD

**Issue by wangzhenhua-bijie** [shardingjdbc/sharding-jdbc#504]
主键占位为空

**Comment by wangzhenhua-bijie** [comment]
private void processGeneratedKey(final List<Object> parameters, final InsertStatement insertStatement, final SQLRouteResult sqlRouteResult) {
        GeneratedKey generatedKey = insertStatement.getGeneratedKey();
        if (parameters.isEmpty()) {
            sqlRouteResult.getGeneratedKeys().add(generatedKey.getValue());
        } else if (parameters.size() == generatedKey.getIndex()) {
            Number key = shardingRule.generateKey(insertStatement.getTables().getSingleTableName());
            parameters.add(key);
            setGeneratedKeys(sqlRouteResult, key);
        } else if (-1 != generatedKey.getIndex()) {
        	Number key = (Number)parameters.get(generatedKey.getIndex());
        	if(key==null) {
        		key = shardingRule.generateKey(insertStatement.getTables().getSingleTableName());
        	}
            setGeneratedKeys(sqlRouteResult, key);
        }
    }

**Comment by terrymanu** [comment]
请提供版本号，报错日志，配置代码和sql

**Comment by wangzhenhua-bijie** [comment]
<sharding-jdbc-core.version>2.0.1</sharding-jdbc-core.version>
@Component
public class UserTableRule extends TableRuleSharding {

	@Value(value="${environment.server.id}")
	private long workerId = 1;
	
	public UserTableRule() {
		super();
		DefaultKeyGenerator.setWorkerId(workerId);
		this.setLogicTable("user");
		this.setActualDataNodes("db1.user_${0..30}");
		// DefaultKeyGenerator.setWorkerId(workerId);
		// 选库规则
		// this.setDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("master_id", "db_${master_id % 2}");
		// 选表规则
		this.setTableShardingStrategyConfig(new ComplexShardingStrategyConfiguration("account", UserTableShardingAlgorithm.class.getName()));
		this.setKeyGeneratorColumnName("user_id");
		this.setKeyGeneratorClass(DefaultKeyGenerator.class.getName());
	}
	
	public static class UserTableShardingAlgorithm implements ComplexKeysShardingAlgorithm {

		@SuppressWarnings("unchecked")
		@Override
		public Collection<String> doSharding(Collection<String> availableTargetNames, Collection<ShardingValue> shardingValues) {
			List<Integer> indexs = new ArrayList<Integer>();
			for (ShardingValue shardingValue : shardingValues) {
				if (StringUtils.equals(shardingValue.getColumnName(), "account")) {//账号hash分库
					for (String account : ((ListShardingValue<String>) shardingValue).getValues()) {
						int index = HashAlgorithms.FNVHash1(account) % availableTargetNames.size();
						if(!indexs.contains(index)) {
							indexs.add(index);
						}
					}
				}
			}
			if (indexs.size()<0) {
				return availableTargetNames;
			}
			final List<String> tables = new ArrayList<String>(availableTargetNames);
			List<String> result = new ArrayList<String>();
			indexs.forEach(e->{
				result.add(tables.get(e));
			});
			return result;
		}
	}

}
public class TableRuleSharding extends TableRuleConfiguration {
	
	@Override
	public TableRule build(Map<String, DataSource> dataSourceMap) {
		TableRule tableRule = super.build(dataSourceMap);
		List<String> actualDataNodes = new InlineExpressionParser(this.getActualDataNodes()).evaluate();
		for (String each : actualDataNodes) {
			DataNode dataNode = new DataNode(each);
			DataSource dataSource =  dataSourceMap.get(dataNode.getDataSourceName());
			this.checkTable(dataSource,this.getLogicTable(),dataNode.getTableName());
		}
		return tableRule;
	}
	
	private void checkTable(DataSource dataSource,String logicTable,String shardingTable) {
		if(dataSource instanceof MasterSlaveDataSource) {
			dataSource = ((MasterSlaveDataSource)dataSource).getMasterSlaveRule().getMasterDataSource();
		}
		Connection connection = null;
		Statement statement = null;
		try {
			connection = dataSource.getConnection();
			statement = connection.createStatement();
			String queryTableSql = String.format("select TABLE_NAME from information_schema.tables WHERE TABLE_NAME = '%s'", shardingTable);
			ResultSet resultSet = statement.executeQuery(queryTableSql);
			if(!resultSet.next()) {
				String sql = String.format("create table %s like %s", shardingTable,logicTable);
				statement.execute(sql);
			}
		} catch (SQLException e) {
			throw new IllegalArgumentException("Create Sharding Table Error:"+logicTable, e);
		}finally {
			try {
				if(statement!=null) {
					statement.close();
				}
				if(connection!=null) {
					connection.close();
				}
			} catch (SQLException e) {
				
			}
		}
	}
	
}
public abstract class DBConfig {
	
	private String mapperLocation;
	
	@Resource
	private ApplicationContext applicationContext;
	
	@Resource
	protected Environment env;
	
	protected void setMapperLocation(String mapperLocation) {
		this.mapperLocation = mapperLocation;
	}

	protected String getMapperLocation(){
		if(mapperLocation==null){
			mapperLocation = StringUtils.removeEnd(this.getClass().getResource("").toString(), "configs/")+"**/*.xml";
		}
		return mapperLocation;
	}
	
	protected abstract DataSource dataSource() throws SQLException;
	
	protected DataSource dataSource(JSONObject datas) throws SQLException {
		ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
		Map<String,DataSource> dataSourceMapAll = new HashMap<String, DataSource>();
		for (String dbName : datas.keySet()) {
			Map<String, DataSource> dataSourceMap = new HashMap<String, DataSource>();
			String masterDataSourceName = null;
			JSONArray dbs = datas.getJSONArray(dbName);
			for (int i = 0; i < dbs.size(); i++) {
				String prefix = dbs.getString(i);
				DataSource dataSource = dataSource(prefix);
				String poolName = dbName+"-"+this.env.getProperty(prefix+".poolName", String.class);
				if(masterDataSourceName==null) {
					masterDataSourceName = poolName;
				}else {
					dataSourceMap.put(poolName, dataSource);
				}
				dataSourceMapAll.put(poolName, dataSource);
			}
			MasterSlaveRuleConfiguration masterSlaveRuleConfig = new MasterSlaveRuleConfiguration();
			masterSlaveRuleConfig.setName(dbName);
			masterSlaveRuleConfig.setMasterDataSourceName(masterDataSourceName);
			if(dataSourceMap.size()>0) {
				for (String dataName : dataSourceMap.keySet()) {
					masterSlaveRuleConfig.getSlaveDataSourceNames().add(dataName);
				}
			}else {//只有一个读写同一个库
				masterSlaveRuleConfig.getSlaveDataSourceNames().add(masterDataSourceName);
			}
			shardingRuleConfig.getMasterSlaveRuleConfigs().add(masterSlaveRuleConfig);
		}
	    Map<String, TableRuleConfiguration> tableRuleMap = this.applicationContext.getBeansOfType(TableRuleConfiguration.class);
	    if(tableRuleMap!=null&&tableRuleMap.size()>0) {
	    	tableRuleMap.forEach((e,v)->{
	    		shardingRuleConfig.getTableRuleConfigs().add(v);
	    		shardingRuleConfig.getBindingTableGroups().add(v.getLogicTable());
	    	});
	    }
	    Properties properties = new Properties();
	    properties.put(ShardingPropertiesConstant.SQL_SHOW.getKey(), env.getProperty("sql.show", Boolean.class, false).toString());
	    return new ShardingDataSource(shardingRuleConfig.build(dataSourceMapAll), new ConcurrentHashMap<String, Object>(), properties);
	}
	
	private DataSource dataSource(String prefix) {
		HikariConfig config = new HikariConfig();
		config.setPoolName(env.getProperty(prefix+".poolName",String.class));
		config.setDriverClassName(env.getProperty(prefix+".driverClassName",String.class));
		config.setJdbcUrl(env.getProperty(prefix+".jdbcUrl",String.class));
		config.setUsername(env.getProperty(prefix+".username",String.class));
		config.setPassword(env.getProperty(prefix+".password",String.class));
		config.setReadOnly(env.getProperty(prefix+".readOnly",Boolean.class));
		config.setConnectionTimeout(env.getProperty(prefix+".connectionTimeout",Long.class));
		config.setIdleTimeout(env.getProperty(prefix+".idleTimeout",Long.class));
		config.setMaxLifetime(env.getProperty(prefix+".maxLifetime",Long.class));
		config.setMaximumPoolSize(env.getProperty(prefix+".maximumPoolSize",Integer.class));
		config.setMinimumIdle(env.getProperty(prefix+".minimumIdle",Integer.class));
		HikariDataSource dataSource = new HikariDataSource(config);
        return dataSource;
    }
	
	protected DataSourceTransactionManager transactionManager(DataSource dataSource) {
        return new DataSourceTransactionManager(dataSource);
    }
	
	protected SqlSessionFactory sqlSessionFactory(DataSource dataSource)
            throws Exception {
        final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource);
        sessionFactory.setMapperLocations(new PathMatchingResourcePatternResolver().getResources(getMapperLocation()));
        sessionFactory.setConfiguration(this.getConfiguration());
        PageInterceptor page = new PageInterceptor();
        Properties properties = new Properties();
        properties.setProperty("reasonable", "true");
        properties.setProperty("offsetAsPageNum", "true");
        properties.setProperty("autoRuntimeDialect", "true");
        properties.setProperty("supportMethodsArguments", "true");
        properties.setProperty("rowBoundsWithCount", "false");
        page.setProperties(properties);
        sessionFactory.setPlugins(new Interceptor[]{page});
        return sessionFactory.getObject();
    }
	
	protected Configuration getConfiguration() {
		Configuration config = new Configuration();
		//使全局的映射器启用或禁用缓存
		config.setCacheEnabled(true);
		//全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
		config.setLazyLoadingEnabled(false);
		//配置默认的执行器。SIMPLE 就是普通的执行器；REUSE 执行器会重用预处理语句（prepared statements）； BATCH 执行器将重用语句并执行批量更新。
		config.setDefaultExecutorType(ExecutorType.REUSE);
		return config;
	}
}

**Comment by wangzhenhua-bijie** [comment]
<insert id="insert" parameterType="com.binance.account.models.user.User">
		insert into user (user_id, account, password,
		salt, is_active, status, auth_key,
		insert_time, update_time, last_login_time,
		lock_end_time)
		values (#{userId,jdbcType=BIGINT}, #{account,jdbcType=VARCHAR},
		#{password,jdbcType=VARCHAR},
		#{salt,jdbcType=CHAR}, #{isActive,jdbcType=BIT}, #{status,jdbcType=INTEGER},
		#{authKey,jdbcType=VARCHAR},
		#{insertTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP},
		#{lastLoginTime,jdbcType=TIMESTAMP},
		#{lockEndTime,jdbcType=TIMESTAMP})
	</insert>

**Comment by wangzhenhua-bijie** [comment]
INFO-2017.12.22 17:11:38 CST [http-nio-9090-exec-1] - [Sharding-JDBC-SQL(59)] - Actual SQL: db1 ::: insert into user_18 (user_id, account, password,
		salt, is_active, status, auth_key,
		insert_time, update_time, last_login_time,
		lock_end_time)
		values (?, ?,
		?,
		?, ?, ?,
		?,
		?, ?,
		?,
		?) ::: [null, 123456@qq.com, string, 1d3aa11291fd4d14aa4769c292bfad63, false, 0, null, 2017-12-22T17:11:38.522+0800, 2017-12-22T17:11:38.522+0800, null, 2017-12-22T17:11:38.522+0800]
ERROR-2017.12.22 17:11:38 CST [http-nio-9090-exec-1] - [com.binance.master.utils.LogUtils(22)] - nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: io.shardingjdbc.core.exception.ShardingJdbcException: io.shardingjdbc.core.exception.ShardingJdbcException: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
### The error may involve com.binance.account.data.user.UserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: insert into user (user_id, account, password,   salt, is_active, status, auth_key,   insert_time, update_time, last_login_time,   lock_end_time)   values (?, ?,   ?,   ?, ?, ?,   ?,   ?, ?,   ?,   ?)
### Cause: io.shardingjdbc.core.exception.ShardingJdbcException: io.shardingjdbc.core.exception.ShardingJdbcException: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: io.shardingjdbc.core.exception.ShardingJdbcException: io.shardingjdbc.core.exception.ShardingJdbcException: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null
### The error may involve com.binance.account.data.user.UserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: insert into user (user_id, account, password,   salt, is_active, status, auth_key,   insert_time, update_time, last_login_time,   lock_end_time)   values (?, ?,   ?,   ?, ?, ?,   ?,   ?, ?,   ?,   ?)
### Cause: io.shardingjdbc.core.exception.ShardingJdbcException: io.shardingjdbc.core.exception.ShardingJdbcException: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'user_id' cannot be null

**Comment by terrymanu** [comment]
看报错是user_id不允许为null，这是数据库底层抛出来的。与sharding jdbc无关。请自行确认user id不为null

**Comment by wangzhenhua-bijie** [comment]
this.setKeyGeneratorColumnName("user_id");
this.setKeyGeneratorClass(DefaultKeyGenerator.class.getName());
不会自动设置主键？

**Comment by wangzhenhua-bijie** [comment]
@terrymanu
