### ISSUE TITLE
在Eclipse启动时报错

### ISSUE THREAD

**Issue by zhengdixu** [shardingjdbc/sharding-jdbc#505]
在浏览器打开http://shardingjdbc.io/schema/shardingjdbc/sharding 报404
在Eclipse启动时报错：Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://shardingjdbc.io/schema/shardingjdbc/sharding]

**Comment by terrymanu** [comment]
请阅读faq
