### ISSUE TITLE
insert 插入时 中间有子查询报错

### ISSUE THREAD

**Issue by wangzhenhua-bijie** [shardingjdbc/sharding-jdbc#507]
insert into sys_config (id, code, `group`,
		value,is_hide, `desc`, order_by,
		insert_time, update_time)
		values (#{id,jdbcType=BIGINT}, #{code,jdbcType=VARCHAR}, #{group,jdbcType=VARCHAR},
		#{value,jdbcType=VARCHAR},#{isHide,jdbcType=BIT}, #{desc,jdbcType=VARCHAR}, (SELECT IFNULL(MAX(sc.order_by),0) FROM sys_config sc WHERE sc.`group` = #{group,jdbcType=VARCHAR}),
		now(), now())

**Comment by terrymanu** [comment]
不支持这样的sql
