### ISSUE TITLE
求教大神，关于分表字段

### ISSUE THREAD

**Issue by yehaihuakai** [shardingjdbc/sharding-jdbc#517]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
2.0.1

  

    请教各位前辈一个关于分表的问题，2.0版本分表字段如果为String类型应该怎么处理，比如 "order20181225"，我想截取后面数字部分用来进行分表。研究了下，没弄明白yaml文件配置的这种情况该怎么写。
还望各位前辈指教

**Comment by terrymanu** [comment]
分片算法都是自定义的，java代码想怎么写都可以。
更多细节请参见example

**Comment by yehaihuakai** [comment]
好的，谢谢
