### ISSUE TITLE
PreciseModuloDatabaseShardingAlgorithm should have public privilege and no argument constructor

### ISSUE THREAD

**Issue by zhengdixu** [shardingjdbc/sharding-jdbc#519]
按example代码配置，启动时却报错:
     org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDatabaseTableDataSource': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [io.shardingjdbc.orchestration.internal.OrchestrationShardingDataSource]: Constructor threw exception; nested exception is io.shardingjdbc.core.exception.ShardingJdbcException: Class com.ly.core.algorithm.PreciseModuloDatabaseShardingAlgorithm should have public privilege and no argument constructor

附代码如下：
<bean id="demo_ds_0" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://localhost:3306/demo_ds_0"/>
        <property name="username" value="root"/>
        <property name="password" value="123456"/>
    </bean>
    
    <sharding:standard-strategy id="databaseShardingStrategy" sharding-column="user_id" precise-algorithm-class="com.ly.core.algorithm.PreciseModuloDatabaseShardingAlgorithm"/>
    <sharding:standard-strategy id="tableShardingStrategy" sharding-column="order_id" precise-algorithm-class="com.ly.core.algorithm.algorithm.PreciseModuloTableShardingAlgorithm"/>
    <sharding:data-source id="shardingDatabaseTableDataSource" registry-center-ref="regCenter">
        <sharding:sharding-rule data-source-names="demo_ds_0">
            <sharding:table-rules>
                <sharding:table-rule logic-table="t_order"  database-strategy-ref="databaseShardingStrategy" table-strategy-ref="tableShardingStrategy" generate-key-column="order_id" />
                <sharding:table-rule logic-table="t_order_item" database-strategy-ref="databaseShardingStrategy" table-strategy-ref="tableShardingStrategy" generate-key-column="order_item_id" />
            </sharding:table-rules>
        </sharding:sharding-rule>
    </sharding:data-source>

package com.ly.core.algorithm;
import io.shardingjdbc.core.api.algorithm.sharding.PreciseShardingValue;
import io.shardingjdbc.core.api.algorithm.sharding.standard.PreciseShardingAlgorithm;

import java.util.Collection;

public class PreciseModuloDatabaseShardingAlgorithm implements PreciseShardingAlgorithm<Integer> {
	
    @Override
    public String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Integer> shardingValue) {
        for (String each : availableTargetNames) {
            if (each.endsWith(shardingValue.getValue() % 2 + "")) {
                return each;
            }
        }
        throw new UnsupportedOperationException();
    }
}

**Comment by terrymanu** [comment]
看报错信息，应该是你自行实现的算法类com.ly.core.algorithm.PreciseModuloDatabaseShardingAlgorithm没提供public的无参构造器所致
