### ISSUE TITLE
动态增加数据源支持吗？

### ISSUE THREAD

**Issue by klaus20141002** [shardingjdbc/sharding-jdbc#527]
Please answer these questions before submitting your issue. Thanks!

**Comment by klaus20141002** [comment]
我使用的版本是  ：<sharding-jdbc.version>2.0.1</sharding-jdbc.version>
希望可以支持动态添加数据源

**Comment by terrymanu** [comment]
支持，请阅读文档和参考example

**Comment by MLeft** [comment]
请问具体在哪个章节或者example?

**Comment by 852675742** [comment]
请问具体在哪个章节或者example?

**Comment by alwyngo** [comment]
@terrymanu Same question，where to find this part document and example codes ?
