### ISSUE TITLE
spring环境用RelaxedPropertyResolver读取inline表达式时报Could not resolve placeholder

### ISSUE THREAD

**Issue by wangjianwen** [shardingjdbc/sharding-jdbc#532]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
sharding-jdbc 2.0.1

### Expected behavior

```java
 RelaxedPropertyResolver resolver = new RelaxedPropertyResolver(environment);
String actualDataNodes= resolver.getProperty("xxx.datasource.sharding.tablerule1.actualDataNodes");
```
期望resolver能读取application.properties中xxx.datasource.sharding.tablerule1.actualDataNodes配置项的值db_${0..1}.t1_${0..5}

### Actual behavior
调用resolver.getProperty("xxx.datasource.sharding.tablerule1.actualDataNodes")时报：

java.lang.IllegalArgumentException: Could not resolve placeholder '0..1' in value "db_${0..1}.receive_detail_${[0, 5]}"

### Steps to reproduce the behavior
由于项目需求，需要自定义sharding配置文件，不能按照官方例子配置，自己解析。所以在项目的application.properties文件中，配置sharding规则如下:

```
xxx.datasource.sharding.tablerule.names=tablerule1
xxx.datasource.sharding.tablerule1.logictable=t1
xxx.datasource.sharding.tablerule1.actualDataNodes=db_${0..1}.t1_${0..5}
xxx.datasource.sharding.tablerule1.databaseShardingStrategyType=standard
xxx.datasource.sharding.tablerule1.databaseShardingStrategy.shardingColumn=id
xxx.datasource.sharding.tablerule1.databaseShardingStrategy.preciseAlgorithmClassName=ModuloDatabaseShardingAlgorithm
xxx.datasource.sharding.tablerule1.tableShardingStrategyType=complex
xxx.datasource.sharding.tablerule1.tableShardingStrategy.shardingColumns=name,id
xxx.datasource.sharding.tablerule1.tableShardingStrategy.algorithmClassName=ModuloTableShardingAlgorithm
```
按照FAQ 2中所说，我添加了如下bean配置

       @Bean
        public PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer() {
            PropertySourcesPlaceholderConfigurer p = new PropertySourcesPlaceholderConfigurer();
            p.setLocations(new ClassPathResource("application.properties"));
            p.setIgnoreUnresolvablePlaceholders(true);
            return p;
        }
也不起作用，怎么破？
@terrymanu 不要直接把我的issue标记为无效

**Comment by terrymanu** [comment]
xxx.datasource.sharding.tablerule.names并非sharding jdbc所提供的spring boot starter。
目前的使用方式：
1. 参考例子，使用sharding jdbc提供的spring boot starter
2. 自行编码，需要自己解决相关问题
