### ISSUE TITLE
查询结果有误

### ISSUE THREAD

**Issue by klaus20141002** [shardingjdbc/sharding-jdbc#533]
Please answer these questions before submitting your issue. Thanks!
俩条sql语句查询结果不一致，猜测是由于t_session_info 分表【5个】导致结果出现错误
同样的查询条件，count(1)结果是1，却查到resultMap是5

### Which version of Sharding-Jdbc do you using?
2.0.1
### Expected behavior
 ==>  Preparing: select count(1) from t_session_info a left join t_session_info_ext b on a.session_id = b.session_id where 1=1 and a.app_id = ? and a.user_id = ? 
 ==> Parameters: 10067(Integer), 12312(String)
 <==      Total: 1
 ==>  Preparing: SELECT * FROM t_session_info a left join t_session_info_ext b on a.session_id = b.session_id where 1=1 and a.app_id = ? and a.user_id = ? order by a.start_time limit ?, ? 
 ==> Parameters: 10067(Integer), 12312(String), 0(Integer), 20(Integer)
 <==      Total: 1
### Actual behavior
 ==>  Preparing: select count(1) from t_session_info a left join t_session_info_ext b on a.session_id = b.session_id where 1=1 and a.app_id = ? and a.user_id = ? 
 ==> Parameters: 10067(Integer), 12312(String)
 <==      Total: 1
 ==>  Preparing: SELECT * FROM t_session_info a left join t_session_info_ext b on a.session_id = b.session_id where 1=1 and a.app_id = ? and a.user_id = ? order by a.start_time limit ?, ? 
 ==> Parameters: 10067(Integer), 12312(String), 0(Integer), 20(Integer)
 <==      Total: 5

**Comment by terrymanu** [comment]
因为每个表都count 1，然后做了累加聚合。
我不确定这样做是否合理，但我也想问一下count(1)使用在什么业务场景？

**Comment by klaus20141002** [comment]
这是分页用的呀，count结果是正确的，后面select是有问题的，感觉和每个表做了笛卡尔积一样

**Comment by terrymanu** [comment]
我没有弄清楚上下文，请提供分片策略的配置，数据库的ddl语句以及数据库相关记录

**Comment by terrymanu** [comment]
看sql的意思应该是t_session_info与t_session_info_ext的分片策略一致？是否忘记配BindingTableRule了？

**Comment by klaus20141002** [comment]
是一致的，按照逻辑表的走查询结果是一条，实际程序返回5条，因为分表是5个，感觉这个是有点问题的
![image](https://user-images.githubusercontent.com/8716969/34552808-c782807e-f15e-11e7-9436-50a8c1805e3e.png)
![image](https://user-images.githubusercontent.com/8716969/34552819-d0c65cb4-f15e-11e7-9e0f-3977213f5c04.png)
![image](https://user-images.githubusercontent.com/8716969/34552873-25ffaf14-f15f-11e7-83be-026078bc0d78.png)

**Comment by klaus20141002** [comment]
![image](https://user-images.githubusercontent.com/8716969/34552894-4183e78c-f15f-11e7-960e-0b0d6f45beff.png)

**Comment by terrymanu** [comment]
请提供分片策略的配置，数据库的ddl语句以及数据库相关记录，以便于我们重现问题并修改

**Comment by klaus20141002** [comment]
config:
      sharding:
        #默认分库策略
        default-database-strategy:
          inline:
            sharding-column: app_id
            algorithm-expression: ds_${10004..10005}
      binding-tables:
          t_session_info,
          t_session_info_ext
        #分库分表配置，可配置多个logic_table_name
       tables:
           t_session_info:
            actual-data-nodes: ds_${10004..10005}.t_session_info_${0..4}
            database-strategy:
              inline:
                sharding-column: app_id
                algorithm-expression: ds_${app_id}
            table-strategy:
              inline:
                sharding-column: channel
                algorithm-expression: t_session_info_${channel}
            key-generator-column-name: id
          t_session_info_ext:
            actual-data-nodes: ds_${10004..10005}.t_session_info_ext_${0..4}
            database-strategy:
              inline:
                sharding-column: app_id
                algorithm-expression: ds_${app_id}
            table-strategy:
              inline:
                sharding-column: channel
                algorithm-expression: t_session_info_ext_${channel}
            key-generator-column-name: id



ddl：
CREATE TABLE `t_session_info_ext_1` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`app_id` INT(11) NOT NULL  ,
	`channel` INT(11) NULL DEFAULT NULL,
	`last_update_timestamp` BIGINT(20) NULL DEFAULT NULL,
	`service_id` VARCHAR(100) NULL DEFAULT NULL,
	`session_id` VARCHAR(100) NULL DEFAULT NULL,
	`session_type` VARCHAR(100) NULL DEFAULT NULL,
	`session_stage` VARCHAR(100) NULL DEFAULT NULL ,
	`end_type` VARCHAR(50) NULL DEFAULT NULL ,
	`evaluation_status` TINYINT(4) NULL DEFAULT '0',
	`evaluation` VARCHAR(500) NULL DEFAULT NULL,
	`evaluation_text` VARCHAR(500) NULL DEFAULT NULL ,
	`evaluation_tags` VARCHAR(500) NULL DEFAULT NULL ,
	`quality_standard_score` VARCHAR(500) NULL DEFAULT NULL ,
	`quality_add_score` VARCHAR(500) NULL DEFAULT NULL ,
	`quality_comment` VARCHAR(500) NULL DEFAULT NULL ,
	`remark` VARCHAR(4000) NULL DEFAULT NULL  ,
	`extends_info` VARCHAR(4000) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	INDEX `session_id` (`session_id`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=153475303384023041
;

CREATE TABLE `t_session_info_1` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`app_id` INT(11) NOT NULL ,
	`channel` INT(11) NOT NULL DEFAULT '0',
	`date_sign` INT(11) NULL DEFAULT NULL ,
	`session_id` VARCHAR(100) NULL DEFAULT NULL ,
	`user_id` VARCHAR(100) NULL DEFAULT NULL ,
	`user_ip` VARCHAR(50) NULL DEFAULT NULL ,
	`user_address` VARCHAR(100) NULL DEFAULT NULL ,
	`start_time` BIGINT(20) NULL DEFAULT NULL ,
	PRIMARY KEY (`id`),
	INDEX `session_id` (`session_id`),
	INDEX `user_id` (`user_id`),
	INDEX `date_sign` (`date_sign`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=153475302507413505
;

**Comment by terrymanu** [comment]
我看每张表的数据量应该很小，能否将insert语句也贴出来，我们就可以直接重现问题了

**Comment by klaus20141002** [comment]
INSERT INTO `t_session_info_1` VALUES (153474391911432192, 10067, 1, 20171229, '10067_10000_1514520226', '12312', '127.0.0.1', 'localhost', 1514520746234);
INSERT INTO `t_session_info_1` VALUES (153475264976781312, 10067, 1, 20171229, '10067_10000_15145202261', '12313', NULL, NULL, 1514520954438);
INSERT INTO `t_session_info_1` VALUES (153475288699764736, 10067, 1, 20171229, '10067_10000_15145202262', '12314', NULL, NULL, 1514520960063);
INSERT INTO `t_session_info_1` VALUES (153475294160748544, 10067, 1, 20171229, '10067_10000_15145202263', '12315', NULL, NULL, 1514520961408);
INSERT INTO `t_session_info_1` VALUES (153475296568279040, 10067, 1, 20171229, '10067_10000_15145202264', '12316', NULL, NULL, 1514520961993);
INSERT INTO `t_session_info_1` VALUES (153475300238295040, 10067, 1, 20171229, '10067_10000_15145202265', '12317', NULL, NULL, 1514520962802);
INSERT INTO `t_session_info_1` VALUES (153475302507413504, 10067, 1, 20171229, '10067_10000_15145202266', '12318', NULL, NULL, 1514520963414);



INSERT INTO `t_session_info_ext_1` VALUES (153475289781895168, 10067, 1, 1514520960377, '23429', '10067_10000_15145202261', NULL, NULL, 'user-end', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `t_session_info_ext_1` VALUES (153475295083495424, 10067, 1, 1514520961638, '23428', '10067_10000_15145202262', NULL, NULL, 'user-end', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `t_session_info_ext_1` VALUES (153475297587494912, 10067, 1, 1514520962206, '23427', '10067_10000_15145202263', NULL, NULL, 'user-end', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `t_session_info_ext_1` VALUES (153475019840684032, 10067, 1, 1514520746574, '234226', '10067_10000_15145202264', NULL, NULL, 'user-end', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `t_session_info_ext_1` VALUES (153475266268626944, 10067, 1, 1514520954680, '23425', '10067_10000_15145202265', NULL, NULL, 'user-end', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `t_session_info_ext_1` VALUES (153475301333008384, 10067, 1, 1514520963084, '23424', '10067_10000_15145202266', NULL, NULL, 'user-end', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `t_session_info_ext_1` VALUES (153475303384023040, 10067, 1, 1514520963621, '23423', '10067_10000_1514520226', '3242', '234', 'user-end', 0, '234', '324', '234', '2342', '234234', '234234', '234234', '23424');
