### ISSUE TITLE
DruidDataSource 数据源时无法正常工作

### ISSUE THREAD

**Issue by zz111333** [shardingjdbc/sharding-jdbc#535]
用BasicDataSource做datasource 可以正常的分库分表 增删改查 
但是用DruidDataSource 就无法删除和插入 但可以查询
debug发现插入数据时lastInsertId 都已经被改了 
但数据库中仍然没有保存下去 用脏读 READ UNCOMMITTED 也查不到
请帮忙分析下是哪里配错了 
感谢

**Comment by terrymanu** [comment]
请提供版本信息以及报错信息

**Comment by terrymanu** [comment]
应该是spring使用的问题，没有配置事务的spring应该不会提交对数据的修改。

**Comment by zz111333** [comment]
无法commit的原因是defaultAutoCommit默认配置是true,改为false则无法自动commit.
但在使用单数据源和mybatis-sptring,如果从datasource取autocommit为false时,mybatis仍然会commit的.
mybatis实现如下.

//mybatis-spring-1.3.0   SpringManagedTransaction
  @Override
  public void commit() throws SQLException {
    if (this.connection != null && !this.isConnectionTransactional && !this.autoCommit) {
      if (LOGGER.isDebugEnabled()) {
        LOGGER.debug("Committing JDBC Connection [" + this.connection + "]");
      }
      this.connection.commit();
    }
  }

 private void openConnection() throws SQLException {
    this.connection = DataSourceUtils.getConnection(this.dataSource);
    this.autoCommit = this.connection.getAutoCommit();
    this.isConnectionTransactional = DataSourceUtils.isConnectionTransactional(this.connection, this.dataSource);
  }


使用sharding-jdbc时,由于在openConnection()并不是创建的datasource配置的值,而是
io.shardingjdbc.core.jdbc.adapter.AbstractConnectionAdapter
其中getAutoCommit()是默认true,所以mybatis就无法自动commit.

请问怎么样能让datasource的defaultAutoCommit为false生效?
谢谢
