### ISSUE TITLE
支持直接通过注册中心读取配置

### ISSUE THREAD

**Issue by haocao** [shardingjdbc/sharding-jdbc#537]
编排支持直接通过注册中心直接读取配置，无需在代码中配置sharding rule及data sources等信息

**Comment by f-zhao** [comment]
这个我这边已经实现，但是场景比较单一，是基于spring的配置，通用性不是很好

**Comment by terrymanu** [comment]
感兴趣的话继续精炼代码，最终就会合并到主干

**Comment by ma-xiao-guang-64** [comment]
现状：
目前通过factory创建datasource需要本地配置，如果本地不存在配置文件创建datasource时会抛空指针异常
提议：
1、创建datasource可以不传入sharding rule，data sources等信息
2、在OrchestrationFacade的init方法中添加从配置中心加载配置的逻辑
3、如果本地配置和从注册中心加载的配置不一样触发datasource的renew方法
