### ISSUE TITLE
对未配置分库分表规则的表，shardingjdbc内部能否自动按defaultDataSource来执行，而不需要做任何配置？

### ISSUE THREAD

**Issue by penggle** [shardingjdbc/sharding-jdbc#538]
你好，本人最近有个项目要考虑到分库分表，但是只是几张大表需要做分库分表，其他表走defaultDataSource，在试用探索过程中发现，没配置任何分库分表规则的表，在执行insert是的时候走defaultDataSource且未报错，但是在执行select查询的时候，报no table route info异常，于是我手动配置了该表的不分库分表配置(如下所示，我使用的是springjdbc)后执行select操作，查询就不报错了并且结果正确。
       `
	<bean id="userTableRuleConfig" class="io.shardingjdbc.core.api.config.TableRuleConfiguration">
		
		<property name="logicTable" value="t_user"/>
		
		<property name="databaseShardingStrategyConfig" ref="noneShardingStrategyConfiguration"/>
		<property name="tableShardingStrategyConfig" ref="noneShardingStrategyConfiguration"/>
		
		<property name="actualDataNodes" value="ds_0.t_user"/>
	</bean>`

大部分情况下，一个项目中只有部分表，少数表需要分库分表，不需要分库分表的表占大多数，如果此类表很多的话，岂不是要像上面那样配置很多这些枯燥的配置，亦或是我配置不对？shardingjdbc是否有其他法子可以免去配置，如果有请劳烦给个demo看看？(Ps：当然DOC文档中的FAQ第8条第2点也是一个解决办法)

**Comment by terrymanu** [comment]
没经过任何解释自己关闭issue，视为无效问题，请知悉
