### ISSUE TITLE
mysql delete语句表名使用别名情况下的问题

### ISSUE THREAD

**Issue by penggle** [shardingjdbc/sharding-jdbc#539]
使用官方demo中的t_order,t_order_item场景，
delete a from t_order_item a where a.order_id = ? and a.user_id = ? and a.item_id = ?；
由于mysql delete语句表名带名别时其书写方式其他数据库不一样，导致ModuloShardingTableAlgorithm的doSharding方法中的tableNames为空集合，shardingValue中logicTableName为a而不是t_order_item，此为明显bug，期望fix

**Comment by haocao** [comment]
目前官方文档https://dev.mysql.com/doc/refman/5.7/en/delete.html中对于别名的使用为多表删除，目前Sharding-JDBC还无法支持。以下为MySQL单表删除语法，是不支持别名的。

Single-Table Syntax

DELETE [LOW_PRIORITY] [QUICK] [IGNORE] FROM tbl_name
    [PARTITION (partition_name [, partition_name] ...)]
    [WHERE where_condition]
    [ORDER BY ...]
    [LIMIT row_count]
