### ISSUE TITLE
查询条件含有is not null的时候分页的结果错误

### ISSUE THREAD

**Issue by luyf1030** [shardingjdbc/sharding-jdbc#541]
Please answer these questions before submitting your issue. Thanks!

###  String sql = "select smUuid, customerId " +
                    "from tbl_app_identify_batch_record t1 " +
                    "where t1.deliverResult IS Not NULL and validateFlag in(1,2,4,5)  " +
                    "and batchId != 0 limit 0, 1";

**Comment by terrymanu** [comment]
fixed at 2.0.2
