### ISSUE TITLE
sharding table not support text type or blob type, 为啥不支持text 和 blob, 且text 映射错误

### ISSUE THREAD

**Issue by zhangyy3** [shardingjdbc/sharding-jdbc#542]
### why not support such column type?

AbstractUnsupportedGeneratedKeysResultSet
and another problem is that , text type mapping to a blob type and throw a exception
sharding jdbc为啥不支持text 和 blob, 且text 映射错误,映射成了blob. 应该映射成varchar再映射成 string
https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-type-conversions.html

**Comment by zhangyy3** [comment]
是2个问题
1. 不支持blob
2. text 映射成了blob,这个问题不确定是哪个环节的问题。待排查，sharding jdbc, mysql driver, mybatis, druid

**Comment by terrymanu** [comment]
1. 精力有限，目前先不支持blob和clob等
2. 不是sharding jdbc的问题
