### ISSUE TITLE
sharding jdbc与jpa结合, 保存获取id异常

### ISSUE THREAD

**Issue by wangfeng-shaw** [shardingjdbc/sharding-jdbc#543]
我使用sharding jdbc与jpa, 在调用jpa的save方法保存对象到分表时, 获取的自增id是异常的, 获取的id是sharding jdbc的分表分片列的值. 我的表有列: id, uid等, 依据uid进行分表, 每次save对象的时候返回的id都是uid的值

以下是spring boot部分配置:
sharding.jdbc.config.sharding.tables.personalize_skill.actual-data-nodes=ds.personalize_skill_${0..99}
sharding.jdbc.config.sharding.tables.personalize_skill.table-strategy.inline.sharding-column=uid
sharding.jdbc.config.sharding.tables.personalize_skill.table-strategy.inline.algorithm-expression=personalize_skill_${uid % 100}
sharding.jdbc.config.sharding.tables.personalize_skill.key-generator-column-name=uid
 请问 是我的配置有问题吗
  
由于目前数据库牵扯的项目组很多, 无法使用sharding jdbc的分布式id, 使用的数据库自增id, 虽然有重复,但目前没有其他影响.

**Comment by terrymanu** [comment]
不支持db的自增主键，如果执意要使用，sharding-jdbc就不对结果进行跟进了。精力有限，望理解

**Comment by wangfeng-shaw** [comment]
好吧 我用last_insert_id解决了
