### ISSUE TITLE
物理分表必须先建立OK是吗？

### ISSUE THREAD

**Issue by wanglongwl** [shardingjdbc/sharding-jdbc#545]
Please answer these questions before submitting your issue. Thanks!

**Comment by terrymanu** [comment]
你好，我没有理解这个问题的意思
是select之前需要先通过create table建表么？

**Comment by terrymanu** [comment]
提问者长时间无跟进，从问题描述看应该是理解问题，并非sharding jdbc的bug，因此关闭了
