### ISSUE TITLE
分表后按不是分表规则的字段 update 和 delete

### ISSUE THREAD

**Issue by zhouxianrongtest** [shardingjdbc/sharding-jdbc#549]
比如我按订单号作为分表字段，但是现在我也db primary key  id字段为条件进行update和delete操作的话，会遍历所有表并且更新了相应表中与id字段值为参数的记录。

请问如何处理这种情况

**Comment by terrymanu** [comment]
我没有看懂，能否在梳理一下问题

**Comment by terrymanu** [comment]
好像是用order id分片，然后按照id删除是吧
看描述是把相关id的数据删了？这个是符合预期的吧

**Comment by zhouxianrongtest** [comment]
sharding：1.5.4.1
mysql 5.7
ibatis

比如订单业务分了100张表，以订单id作为分片规则，但是现在执行
update order  set field = value  where id = 1;
delete order where id = 1;

这样就会遍历100张表, 并且把表中id =1 的记录全部更新

**Comment by terrymanu** [comment]
这是正确的行为吧

**Comment by zhouxianrongtest** [comment]
不符合预期，能不能有什么方法在检查到这个update  or delete是以id作为where条件或者 sql(statmentUnit)> 1 时throw Exception.

看了源码ShardingPreparedStatement之后，

private Collection<PreparedStatementUnit> route() throws SQLException {
        Collection<PreparedStatementUnit> result = new LinkedList<>();
        routeResult = routingEngine.route(getParameters());
        for (SQLExecutionUnit each : routeResult.getExecutionUnits()) {
            SQLType sqlType = routeResult.getSqlStatement().getType();
            Collection<PreparedStatement> preparedStatements;
            if (SQLType.DDL == sqlType) {
                preparedStatements = generatePreparedStatementForDDL(each);
            } else {
                preparedStatements = Collections.singletonList(generatePreparedStatement(each));
            }
            routedStatements.addAll(preparedStatements);
            for (PreparedStatement preparedStatement : preparedStatements) {
                replaySetParameter(preparedStatement);
                result.add(new PreparedStatementUnit(each, preparedStatement));
            }
        }
        return result;
    }

这个方法感觉可以作一个修改，但是此为为final， 不能重载

**Comment by terrymanu** [comment]
delete order where id = 1;然后把所有的id=1的都删了，难道不是期望行为么？
如果不是，期望行为是什么

**Comment by zhouxianrongtest** [comment]
按正确应该是  updateByOrderId or deleteByOrderId， 但是怕误写代码写成了  updateById or deleteById， 会造成数据破坏问题

**Comment by terrymanu** [comment]
这是业务行为，sharding-jdbc只是忠实执行sql而已，因此我们无法针对业务进行任何修改，望理解
