### ISSUE TITLE
yml配置的sql.show一处歧义

### ISSUE THREAD

**Issue by StruggleYang** [shardingjdbc/sharding-jdbc#550]
我按照官网的配置sql.show配置，程序并没有在控制台打印，官网配置如下:
![](http://oqr3htxnb.bkt.clouddn.com/18-1-11/20512396.jpg)
后来查看源码有一处，对于此配置的判断如下:
![](http://oqr3htxnb.bkt.clouddn.com/18-1-11/96023733.jpg)
这个地方我觉得算一个配置歧义，或者文档错误，或许稍加声明避免有人踩这样的坑.

**Comment by haocao** [comment]
这个源码是java.util.Properties里面的，这个问题已经在#521中修复，会在2.0.2版本发布。
