### ISSUE TITLE
子查询报错，无法识别只查询返回的字段

### ISSUE THREAD

**Issue by klaus20141002** [shardingjdbc/sharding-jdbc#551]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
2.0.1
### Expected behavior
normal result map
### Actual behavior
 Unknown column 'a.session_time' in 'field list'
### Please provide the reproduce example codes (such as github link) if possible.

select a.app_id as appId,a.date_sign as dateSign, a.service_id as serviceId,avg(a.session_time) as avgSessionTime from (    select app_id,date_sign, service_id,session_id,sum(answer_time_used) as session_time    from t_session_info_time_stat 
where 1=1    
and app_id = ‘’
and date_sign = ‘’
and service_id = ''   
group by app_id,date_sign,service_id,session_id   ) as a
 group by a.app_id,a.date_sign, a.service_id   ;

**Comment by terrymanu** [comment]
不支持子查询
