### ISSUE TITLE
下载源码后编译报错

### ISSUE THREAD

**Issue by 18357136930** [shardingjdbc/sharding-jdbc#552]
下载整个项目，导入ID后sharding-jdbc-orchestration模块编译报错，如下截图：
![image](https://user-images.githubusercontent.com/19309105/34863782-25464e04-f7ac-11e7-8d9a-42143d13c971.png)
说etcdserverpb相关类找不到，请问这个用的是哪个jar？

**Comment by haocao** [comment]
FAQ已更新，详情参见http://shardingjdbc.io/docs/01-start/faq/
