### ISSUE TITLE
是不是不接受没有单元测试的bugfix比较合理

### ISSUE THREAD

**Issue by neil4dong** [shardingjdbc/sharding-jdbc#554]
在release 文档中出现有些问题 ：https://github.com/shardingjdbc/sharding-jdbc/blob/dev/RELEASE-NOTES.md

https://github.com/shardingjdbc/sharding-jdbc/issues/308
在修复后，过了一两个小版本就只就出现了同一个地方的问题。
https://github.com/shardingjdbc/sharding-jdbc/issues/356
这个100%是没有单元测试导致的。

建议是否可以采用mysql-jdbc-connector的单元测试，去掉不明确不支持的部分。 
sharding-jdbc在使用以来最大的感受就是，问题比较多，已经报告了好几个不过了。
祝越来越好

**Comment by terrymanu** [comment]
谢谢建议。
我们会尽量写单元测试，目前测试覆盖率80%以上，应该是已知开源项目中测试覆盖率比较高的（大部分都是20%）
我们未来也会对代码更多的单元测试
