### ISSUE TITLE
可配置显示分片执行SQL、MasterSlave等日志

### ISSUE THREAD

**Issue by LilyBlooper** [shardingjdbc/sharding-jdbc#560]
### Which version of Sharding-Jdbc do you using?
2.0.1

### Expected behavior
DEBUG模式，或者提供某个开关。 
能够打印 shard，master-slave 等 路由信息。 
我方可以确定具体某个sql 从哪里走

### Actual behavior
DEBUG模式下， 打印的只是某个 MasterSlaveDatesource@xxxx  实例。
没有复写 toString 方法。 或者我用的不对

### Steps to reproduce the behavior
任意SQL，我是只配了主从。

### Please provide the reproduce example codes (such as github link) if possible.
不需要

**我看了之前有个关闭的issue ： [256](https://github.com/shardingjdbc/sharding-jdbc/issues/256)**

**是不是需要依赖skywalk 这套 apm系统？**
**我看了 1.5.0.M2 ，没有发现相关提示或者文档位置**

**Comment by terrymanu** [comment]
已经关闭的issue，功能当然是已实现。请阅读文档，查询sql.show相关关键字

**Comment by YooLin** [comment]
如果是只配置读写分离，那么即便配置了sql.show=true也不会打印日志吧，找了下源码也没翻到  @terrymanu
