### ISSUE TITLE
HintManager 路由错误

### ISSUE THREAD

**Issue by xmh51** [shardingjdbc/sharding-jdbc#562]
版本：1.5.4.1
问题：在多线程情况下，某个线程首次调用 HintManager 进行 强制路由某个逻辑表时，却拿到一个错误的物理库表的数据，第二次调用就正常了。

**Comment by terrymanu** [comment]
请提供可供重现的代码至github，并将连接发送至这里

**Comment by xmh51** [comment]
`public List<Mapping> fetchByCustomId(Integer fetchSize, Long startId, int no) {
try (HintManager hintManager = HintManagerUtil.getInstance()) {
   hintManager.addDatabaseShardingValue("xid_mapping", "xid", String.valueOf(no));
   hintManager.addTableShardingValue("xid_mapping", "xid", String.valueOf(no));
   Example example = new Example(Mapping.class);
   example.createCriteria().andGreaterThan("id", startId);
   List<Mapping> mappings = this.selectByExampleAndRowBounds(example, new RowBounds(0, fetchSize));
   return Mappings;
}
}`  开启多线程访问这段方法，Mapping 是分库分表的。

**Comment by terrymanu** [comment]
请将可运行的代码提交至github，我们无法根据代码片段重现这个问题。
另外，1.x版本已经不再更新，能否使用2.x版本重现此问题？

**Comment by xmh51** [comment]
等周末我看下，能否在 2.x f复现。

**Comment by linrongbin16** [comment]
@xmh51 ，HintManager里的方法没有做多线程的处理，多线程环境下可能有bug啊

**Comment by xmh51** [comment]
@terrymanu  不好意思，周末加班，最近比较忙，没时间复现该问题，麻烦关了吧。

**Comment by terrymanu** [comment]
@xmh51 HintManager使用的threadlocal，请问多线程下会有什么bug？
