### ISSUE TITLE
Lexer只实例化一个Tokenizer

### ISSUE THREAD

**Issue by hongfuli** [shardingjdbc/sharding-jdbc#565]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
current dev branch

优化：在Lexer词法分析时，每个`io.shardingjdbc.core.parsing.lexer.Lexer`可以对应只持有一个`io.shardingjdbc.core.parsing.lexer.analyzer.Tokenizer`对象，没必要每次`nextToken`重新实例化一个。因为在解析工作时，offset的推进应该是两者保持一致的。
不知道我理解的对不对？

**Comment by terrymanu** [comment]
目前考虑，即使大量的new Tokenizer的朝生夕灭的对象，也是进行速度很快的young gc，应该不会导致full gc，进而大幅影响性能。
因此，不使用new，而是复用Tokenizer，是否有相关的性能测试报告，能确定带来了性能的提升？

**Comment by terrymanu** [comment]
并无本质提供就先不合并修改核心的代码了
