### ISSUE TITLE
主键冲突

### ISSUE THREAD

**Issue by klaus20141002** [shardingjdbc/sharding-jdbc#575]
Please answer these questions before submitting your issue. Thanks!
 com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '162887478624124928' for key 'PRIMARY'
### Expected behavior
不知道为啥会出现主键冲突的情况
### Please provide the reproduce example codes (such as github link)

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example

**Comment by terrymanu** [comment]
应用代码导致的主键冲突，请自行解决

**Comment by klaus20141002** [comment]
这个问题是由于分布式部署的时候发生的，即俩台应用服务器都有部署

**Comment by cxdhefei** [comment]
I have the same problem as you @olderzhou ，Distributed deployment will emerge！！
