### ISSUE TITLE
yaml配置换行问题

### ISSUE THREAD

**Issue by klaus20141002** [shardingjdbc/sharding-jdbc#577]
Please answer these questions before submitting your issue. Thanks!

获取数据源换行
String dataSources = propertyResolver.getProperty("names");

建议   OrchestrationSpringBootConfiguration文件

line77

String dataSources = propertyResolver.getProperty("names");

加一个去空格处理

改为  String dataSources = propertyResolver.getProperty("names").trim();

### Please provide the reproduce example codes (such as github link)

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example

**Comment by terrymanu** [comment]
能否提供具体配置。yaml的配置还可以换行么？即使换行，trim也是处理空格，可以处理换行么？

**Comment by klaus20141002** [comment]
yaml支持换行的  
![image](https://user-images.githubusercontent.com/8716969/35368259-6dd083f4-01bd-11e8-872b-bd19651f567c.png)cnak
参考http://www.ruanyifeng.com/blog/2016/07/yaml.html?f=tt
由于换行会转换为空格，所以处理过程会出错

**Comment by terrymanu** [comment]
感谢提供参考意见。能否提供pull request，使您成为sharding-jdbc的贡献者。
谢谢

**Comment by terrymanu** [comment]
fixed at 2.0.3
