### ISSUE TITLE
DDL 异常

### ISSUE THREAD

**Issue by klaus20141002** [shardingjdbc/sharding-jdbc#581]
Please answer these questions before submitting your issue. Thanks!

使用读写分离配置，alter表的时候，应该只更新master 连接对应的表就可以，现在是同时还会更新slave对应的表

    private Collection<PreparedStatement> generatePreparedStatementForDDL(final SQLExecutionUnit sqlExecutionUnit) throws SQLException {
        Collection<PreparedStatement> result = new LinkedList<>();
        Collection<Connection> connections = getConnection().getAllConnections(sqlExecutionUnit.getDataSource());
        for (Connection each : connections) {
            result.add(each.prepareStatement(sqlExecutionUnit.getSql(), resultSetType, resultSetConcurrency, resultSetHoldability));
        }
        return result;
    }
### Which version of Sharding-Jdbc do you using?
2.0.2
### Expected behavior
只更新master表结构
### Please provide the reproduce example codes (such as github link)

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example

**Comment by terrymanu** [comment]
你好，我画了两个小时的时间把所有的example都过了一遍，没有发现你说的问题。
如果你认为仍然有问题，请提供可重现的代码并reopen这个issue，供我们重现，谢谢

**Comment by terrymanu** [comment]
duplicate with #522
