### ISSUE TITLE
About DDL Issue

### ISSUE THREAD

**Issue by klaus20141002** [shardingjdbc/sharding-jdbc#582]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
2.0.2
### Expected behavior
DDL 语句只在master数据源执行
### Actual behavior
DDL在master与slave都会执行导致duplication issue
### Steps to reproduce the behavior
 @terrymanu #581 #570 
1. 在OrderMapper.xml中加一个方法，
    <update id="alterTable">
        ALTER TABLE t_order
		ADD COLUMN order_no VARCHAR(50) NULL COMMENT 'order no , seq rule: random(10)+timestamp' AFTER status;

    </update>
对应的
void alterTable();

2. demoservice添加测试方法

    public void testAlterOrder() {
    	System.out.println("test alter tables started ...........");
    	orderRepository.alterTable();
    }
3. SpringBootDataMybatisMain  中添加调用
applicationContext.getBean(DemoService.class).testAlterOrder();

![image](https://user-images.githubusercontent.com/8716969/35478797-a28ef772-0421-11e8-9b25-c89be9e6da4f.png)

![image](https://user-images.githubusercontent.com/8716969/35478808-245293cc-0422-11e8-9b42-6aa2f469c53a.png)

### Please provide the reproduce example codes (such as github link)

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
基于 example中  sharding-jdbc-spring-boot-data-mybatis-example

**Comment by klaus20141002** [comment]
<update id="alterTable">
        ALTER TABLE t_order
		ADD COLUMN order_no VARCHAR(50) NULL COMMENT 'order no , seq rule: random(10)+timestamp' AFTER status;

    </update>
@terrymanu 看到你的回复很开心，希望这个sharding-jdbc越来越好。

**Comment by terrymanu** [comment]
感谢提供例子，我们再试一下

**Comment by terrymanu** [comment]
我看一一下报错信息，并不是只读的库不能写入这样的错误，
而是你添加的order_no添加重复，
这个order_no添加重复是怎么回事？是主库报出来的还会从库？
你的读写分离是怎么配置的？请贴出来看看

**Comment by klaus20141002** [comment]
![image](https://user-images.githubusercontent.com/8716969/35494982-61b90a20-04f9-11e8-86b7-b16d1c3121ce.png)
从sqlyuj语句看也是master && slave都有执行更新表结构的

**Comment by terrymanu** [comment]
读写分离配置一个数据源这种明显错误的做法，我们就不改了。

**Comment by terrymanu** [comment]
duplicate with #522
