### ISSUE TITLE
没有反引号的列名count被解析为DefaultKeyword.COUNT

### ISSUE THREAD

**Issue by linrongbin16** [shardingjdbc/sharding-jdbc#585]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?

dev

### Expected behavior

在MySQLLexerTest单元测试中：
INSERT INTO t_good (id, name, count, price) VALUES(1, 'Book', 13, 23.55);
上面的语句将count解析为DefaultKeyword.COUNT。

### Actual behavior

我觉得应该解析为Literals.IDENTIFIER，因为count在这里并不表示SQL关键字，而是一个列名。
详见pull request：https://github.com/shardingjdbc/sharding-jdbc/pull/584

**Comment by terrymanu** [comment]
这个是正确的。
因为sharding jdbc将sql解析分为词法解析和语法解析，lexer是词法解析，只是将sql根据字典拆分为一个个的词，不一定完全准确。在语法解析中，才会针对上下文进行处理
