### ISSUE TITLE
exists解析出错

### ISSUE THREAD

**Issue by klaus20141002** [shardingjdbc/sharding-jdbc#586]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
2.0.2
### Expected behavior
正确识别分表
### Actual behavior
Table 'ds_10071.t_chat_log' doesn't exist

t_chat_log  配置分表   t_chat_log_{201801..201812}, 分表字段是：date_month

子查询
and exists( select 1 from t_chat_log where date_month = 201801 )

### Steps to reproduce the behavior

核心即exists路由出错

### Please provide the reproduce example codes (such as github link)

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example

**Comment by terrymanu** [comment]
不支持这样的子查询，请先阅读文档
