### ISSUE TITLE
About DDL Issue 确实有问题

### ISSUE THREAD

**Issue by klaus20141002** [shardingjdbc/sharding-jdbc#588]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.2

### Expected behavior （您预期的结果是）

ddl只在master执行
### Actual behavior （实际运行的结果是）

ddl在master  & slave均有执行
### Steps to reproduce the behavior （可重现问题的操作步骤）
很简单的做法，比如你执行一个创建tables的脚本，检查发现master与slave均有创建。

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by terrymanu** [comment]
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题。为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭。

**Comment by terrymanu** [comment]
duplicate with #522
