### ISSUE TITLE
不支持begin方式开启事务

### ISSUE THREAD

**Issue by wo23wo32** [shardingjdbc/sharding-jdbc#591]
因为采用dbproxy中间件，由dbproxy维持到mysql的connection。为了复用连接，不支持autocommit=0的方式开启事务，只能显式执行begin来开启事务。
但是sharding-jdbc没有实现begin或start transaction的MySQLParser。

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
1.5.4.1

### Expected behavior （您预期的结果是）
可以正常执行statement.executeUpdate("BEGIN");

### Actual behavior （实际运行的结果是）
报异常com.dangdang.ddframe.rdb.sharding.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'BEGIN'.

### Steps to reproduce the behavior （可重现问题的操作步骤）
执行statement.executeUpdate("BEGIN");

**Comment by terrymanu** [comment]
duplicate with #600
