### ISSUE TITLE
sql中对于 0+10 这种计算,sql parse没正确解析

### ISSUE THREAD

**Issue by jklliang** [shardingjdbc/sharding-jdbc#593]
SELECT * FROM (SELECT A1.*, ROWNUM RN1 FROM (SELECT * FROM t_order_item ORDER BY user_id,order_item_id DESC) A1
WHERE ROWNUM <= 0+10  ) B WHERE B.RN1 >= 1

oracle 这种分页写法不支持，Limit 类rewrite方法报空指针，原因在于0+10  ,sql parse没正确解析

**Comment by terrymanu** [comment]
对于互联网应用来说，更加倾向于将计算放入应用而非数据库。
我们精力有限，无法将80%的精力放在余下的20%需求上。
因此我们暂时无法对其进行处理。
如果你有兴趣和时间，欢迎提供pr。
