### ISSUE TITLE
使用行级锁同一个线程的其他语句都不能修改哪行数据了，切换普通数据源可以正常修改

### ISSUE THREAD

**Issue by sunjunhui520** [shardingjdbc/sharding-jdbc#594]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by sunjunhui520** [comment]
Sharding-Jdbc版本2.0.1

**Comment by terrymanu** [comment]
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题。为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭。
