### ISSUE TITLE
Limit查询到的结果集数量与期望值不一致

### ISSUE THREAD

**Issue by lialatd** [shardingjdbc/sharding-jdbc#595]
Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）

当前试用版本为 2.0.3-SNAPSHOT
Expected behavior （您预期的结果是）
逻辑分表：resource_file
实际表：resource_file_2017_10 ~ resource_file_2018_02 
分片字段：SHARDTIME
分片策略：按照月份分表
每张分表中都有大量数据，查询语句如下：
SELECT * FROM resource_file WHERE SHARDTIME BETWEEN ‘2017-10-01’ AND ‘2018-02-06’ LIMIT 0,30；

期待返回的结果集数量为 30 条

Actual behavior （实际运行的结果是）

实际返回的结果集数量为 150 条

实际情况下是将每张分表中的结果集直接合并一起返回，即便是加上排序规则，也只是对每张分表查询到的结果集排序之后直接合并返回，最后得到的结果只是部分有序，请问一下这个能修复吗？

**Comment by terrymanu** [comment]
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题。为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭。
