### ISSUE TITLE
是否支持逻辑分区

### ISSUE THREAD

**Issue by sagkanon** [shardingjdbc/sharding-jdbc#599]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

请问在分库分表的基础上，是否支持逻辑分区？
比如说数据库分8个db_0, db_1, db_2... db_7,  表的话64个 table_0, ... table_63, 对于具体的某个表table_0...table_63，想根据时间进行逻辑分区，比如说按周分区，table_0_2018_1, table_0_2018_2等。

目前2.0.2版本是否能够实现这种效果?

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by terrymanu** [comment]
可以，分片策略是自己写的，灵活性很高，多少个分区维度都可以。
