### ISSUE TITLE
HUGO提升

### ISSUE THREAD

**Issue by terrymanu** [shardingjdbc/sharding-jdbc#604]
当前Sharding-JDBC使用hugo进行文档生成。使用2.x版本的theme已经无法用当前的3.x版本生成html，并且也仍有美化的空间。因此征询志愿者领取任务，感兴趣的同学欢迎联系我。

**Comment by terrymanu** [comment]
done， upgrade hugo to 3.x version

**Comment by leewangq** [comment]
how to build ShardingSphere website by means of hugo and hugo theme learn?can you give me some suggestions
