### ISSUE TITLE
根据表名路由到不同的数据库

### ISSUE THREAD

**Issue by ztgoto** [shardingjdbc/sharding-jdbc#612]
###  version: 2.0.2
这几天看到 分表分库 TableRuleConfiguration，针对的是对表数据进行分表分库。

但现在有如下简单业务场景
1.单表数据不分表也不分库
2.两种不同的业务表根据某种表名规则分布在两个数据库中，比如 t_user_*** 在user库中,t_config_*** 在config库中
3.现在要对sql中满足这些表名的规则的语句做相应的路由（指定表名规则而不是像TableRuleConfiguration指定具体的逻辑表名，通过列名和值来做分发）
这种场景现在是否可以依赖该库的功能实现

或者说我希望有一种类似自己插入自定义拦截器的功能，通过拦截器由我自己来拦截分析修改语句，来指定到不同的数据源连接

**Comment by terrymanu** [comment]
可以使用hint
