### ISSUE TITLE
Please considering make the project description objective

### ISSUE THREAD

**Issue by wu-sheng** [shardingjdbc/sharding-jdbc#613]
I am looking at the http://shardingjdbc.io/index.html . There is a sentence makes me attention:
>  migrate legacy code almost zero costs

I prefer to re-consider about this. I understand zero costs based on JDBC interfaces compatible, and sharding based on SQL statement analysis. But I have to say there are costs from the design level, which definitely far from zero. And if a traditional system using join or some other complex sql features, it is hard to switch into Sharding MySQL (not just sharding-jdbc) easily.

In my perspective, I prefer `compatible with JDBC and ORM frameworks`

**Comment by terrymanu** [comment]
Yes, I accept it is not always zero costs if complicated SQL in legacy code, "zero costs" is the final objective.
I will change the doc to "compatible with JDBC and ORM frameworks" for now. Thank you for suggestion.

**Comment by wu-sheng** [comment]
homepage has updated. Closing this issue.
