### ISSUE TITLE
Starting a developer group

### ISSUE THREAD

**Issue by wu-sheng** [shardingjdbc/sharding-jdbc#615]
# Proposal
Invite trusted contributors, open source lovers and company/sponsor employees to join the developer group. And begin to run the project in an open and self-govern way.

At least set `Committers` group and `Contributors` list, if not ready for PMC. But be advised, Committers and Contributors are not just related about codes. Community development, article writers, important end users are all important。

**Comment by terrymanu** [comment]
I create 2 teams for Committers and Contributors

**Comment by ma-xiao-guang-64** [comment]
I want to do something for sj

**Comment by wu-sheng** [comment]
I recommend contributors should stay in an open list. I didnt need to invite every contributor into the org.

**Comment by wu-sheng** [comment]
If you don't create PMC team, please make sure every committer have right to vote.

**Comment by wu-sheng** [comment]
@ma-xiao-guang-64 welcone, look like you are already a collaborator. Assume you are a committer, right?

**Comment by terrymanu** [comment]
add https://github.com/shardingjdbc/sharding-jdbc/blob/dev/Organization.md

**Comment by wu-sheng** [comment]
Closing. The teams are on building.
