### ISSUE TITLE
sharding-jdbc-core-spring-boot-starter 引入后 空指针异常

### ISSUE THREAD

**Issue by chuibilong** [shardingjdbc/sharding-jdbc#616]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
	<dependency>
			<groupId>io.shardingjdbc</groupId>
			<artifactId>sharding-jdbc-core-spring-boot-starter</artifactId>
			<version>2.0.3</version>
	</dependency>

### Expected behavior （您预期的结果是）
我引入这个jar，没有配置任何东西，不应该报错

### Actual behavior （实际运行的结果是）
![image](https://user-images.githubusercontent.com/22720067/36638881-c95f3cf2-1a3a-11e8-8a80-85b2d25c25bd.png)

### Steps to reproduce the behavior （可重现问题的操作步骤）
![image](https://user-images.githubusercontent.com/22720067/36638888-e307bba2-1a3a-11e8-9a3b-1b41628d4670.png)

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by terrymanu** [comment]
为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭
