### ISSUE TITLE
FindBugs 警告:Bug: Return value of putIfAbsent is ignored, but count is reused in RoundRobinMasterSlaveLoadBalanceAlgorithm.getDataSource(String, String, List) 

### ISSUE THREAD

**Issue by yujiaao** [shardingjdbc/sharding-jdbc#626]
Bug: Return value of putIfAbsent is ignored, but count is reused in io.shardingjdbc.core.api.algorithm.masterslave.RoundRobinMasterSlaveLoadBalanceAlgorithm.getDataSource(String, String, List)
The putIfAbsent method is typically used to ensure that a single value is associated with a given key (the first value for which put if absent succeeds). If you ignore the return value and retain a reference to the value passed in, you run the risk of retaining a value that is not the one that is associated with the key in the map. If it matters which one you use and you use the one that isn't stored in the map, your program will behave incorrectly.
Rank: Scary (8), confidence: High
Pattern: RV_RETURN_VALUE_OF_PUTIFABSENT_IGNORED 
Type: RV, Category: MT_CORRECTNESS (Multithreaded correctness)

不知这个是会带来问题, 请核查.

**Comment by terrymanu** [comment]
please ignore find-bug's warn

**Comment by yujiaao** [comment]
俺有点强迫症
