### ISSUE TITLE
slave的轮询没有起作用

### ISSUE THREAD

**Issue by dotyso** [shardingjdbc/sharding-jdbc#634]
使用的Sharding-Jdbc版本为？
2.0.3

使用以下配置，slave的轮询没有起作用
[MasterSlaveShardingByUserId.txt](https://github.com/shardingjdbc/sharding-jdbc/files/1784574/MasterSlaveShardingByUserId.txt)

  masterSlaveRules:
    ds:
      masterDataSourceName: ds_master_0
      slaveDataSourceNames: [ds_master_0_slave_0, ds_master_0_slave_1]
      loadBalanceAlgorithmType: ROUND_ROBIN

实际运行的结果是
只会返回一个Slave，上例为：ds_master_0_slave_0

**Comment by terrymanu** [comment]
Please reference issue template, provide source code to be reproduce. Thank you.

**Comment by terrymanu** [comment]
no response for long time, close it for now
