### ISSUE TITLE
使用DefaultKeyGenerator，在请求少时只分配到偶数序号表

### ISSUE THREAD

**Issue by dotyso** [shardingjdbc/sharding-jdbc#635]
您使用的Sharding-Jdbc版本为？
2.0.3

提供的DefaultKeyGenerator，在多数低频请求（10毫秒以上）的情况下都是生成偶数的值，而不是奇偶间隔的
如果这样，插入数据时用取模的方式分配到目标表，很容易造成多数集中在偶数表中，造成分配的记录不均匀

请问这种有没有好的方式解决

**Comment by terrymanu** [comment]
please faq：http://shardingjdbc.io/docs_cn/01-start/faq/

**Comment by terrymanu** [comment]
duplicate with #571
