### ISSUE TITLE
项目跑不起来 java.sql.SQLException: No database selected

### ISSUE THREAD

**Issue by jameschopin** [shardingjdbc/sharding-jdbc#644]
代码例子 是两个字段的 example
多字段 我这么写的
![image](https://user-images.githubusercontent.com/20330905/37448692-5fbb0692-2862-11e8-8db5-6ce393da85a2.png)

**Comment by jameschopin** [comment]
求高手！！！

**Comment by terrymanu** [comment]
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题。为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭

**Comment by jameschopin** [comment]
![image](https://user-images.githubusercontent.com/20330905/37448866-15328c8e-2863-11e8-81f6-747c529f7396.png)
why no database 。。
