### ISSUE TITLE
GroupByClauseParser解析问题

### ISSUE THREAD

**Issue by hongfuli** [shardingjdbc/sharding-jdbc#645]
io.shardingjdbc.core.parsing.parser.clause.GroupByClauseParser#addGroupByItem
第84行是不是笔误写错了
`SQLUtil.getExactlyValue(sqlPropertyExpression.getOwner() + "." + SQLUtil.getExactlyValue(sqlPropertyExpression.getName()`
改成 `SQLUtil.getExactlyValue(sqlPropertyExpression.getOwner().getName() + "." + SQLUtil.getExactlyValue(sqlPropertyExpression.getName()`
但是我改过来后，parsing模块测试用例没问题，其它集成单元测试跑不过

**Comment by terrymanu** [comment]
谢谢你的反馈。这里确实有问题，导致补列不正确。我们会在这个版本中修改。
Thanks for your feed back. There is problem here, will cause derive column error. we will fix it next release.
