### ISSUE TITLE
SelectItem should be annotated by EqualsAndHashCode

### ISSUE THREAD

**Issue by hongfuli** [shardingjdbc/sharding-jdbc#648]
I found that there are several subclasses implement  `SelectItem`. They are used as container elements in  `Set` collection(io.shardingjdbc.core.parsing.parser.sql.dql.select.SelectStatement#items), but I only see the `AggregationSelectItem` has `EqualsAndHashCode` annotation. the others are forgotten?

**Comment by terrymanu** [comment]
I checkout the code, you are correct. we should add @EqualsAndHashCode on other SelectItem.
Cloud you test on this and submit a pull request for us? welcome to be a contributor.
