### ISSUE TITLE
只分库不分表，非读写分离情况下

### ISSUE THREAD

**Issue by xieyanze** [shardingjdbc/sharding-jdbc#659]
在只分库不分表的情况下，如何配置？是否需要添加所有表的TableRuleConfiguration？
测试了下 如果只配置setDefaultTableShardingStrategyConfig， 会报异常：
Caused by: java.lang.IllegalStateException: no table route info

**Comment by terrymanu** [comment]
please read document:http://shardingjdbc.io/docs_en/01-start/faq/ or http://shardingjdbc.io/docs_cn/01-start/faq/, 8th question

**Comment by chncho** [comment]
方法1：配置default-data-source，凡是在默认数据源中的表可以无需配置在分片规则中，Sharding-JDBC将在找不到分片数据源的情况下将表路由至默认数据源。
【该方法，不路由的表，也会有sql兼容性检查，对于不支持的sql会报异常】
方法2：将不参与分库分表的数据源独立于Sharding-JDBC之外，在应用中使用多个数据源分别处理分片和不分片的情况。
【该方法，程序中会存在两个数据源，两个数据源之间无法保证事务一致性】
