### ISSUE TITLE
支持不同子库里子表名不同吗？

### ISSUE THREAD

**Issue by Coven2014** [shardingjdbc/sharding-jdbc#664]
你好  请问分库分表的配置规则，支持子表名都不同的情形吗，比如4分片2分库这样的库表组成：
db_0 {tb_0, tb_1}, db_1 {tb_2, tb_3}  ，
现实的场景是订单表计划分片512 { order_0~511}，分到32个子库里，每个子库16张字表。
 @terrymanu  @haocao

**Comment by terrymanu** [comment]
yes, please read document for more details

**Comment by Coven2014** [comment]
有inline表达式那种简单配置方式吗，不是枚举式的全列出来，毕竟有512个分片。
