### ISSUE TITLE
Using stream buffer to process COM_QUERY & STMT_EXECUTE response

### ISSUE THREAD

**Issue by terrymanu** [shardingjdbc/sharding-jdbc#675]
For MySQL protocol, Sharding-Proxy finish COM_QUERY Response's fetch all data, but  GET_MORE_CLIENT_DATA still not implemented yet.

**Comment by tuohai666** [comment]
After a short investigation, I found that GET_MORE_CLIENT_DATA is talking about to transfer a file to MySQL server. Did you intend to do this?
As to get more data from MySQL, I tried 'setFetchDirection' and 'setFetchSize' method in JDBC, and found nothing differenct from packet captured by tcpdump. I doubt the MySQL server don't support this feature. I'll start a deeper study for it later.

**Comment by tuohai666** [comment]
This test base on my runnable code just completed, and shows the difference of memory usage between stream ResultSet and non-stream ResultSet.

sharding-proxy are running on my PC with VM options:
-server -Xmx1g -Xms1g -Xmn128m -Xss256k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=99

5 clients connect to a sharding-proxy, each of the clients select 150000 rows concurrently.
non-stream ResultSet:
![resultset](https://user-images.githubusercontent.com/24643893/39034408-de27d700-44a8-11e8-9998-7b875fdef6b6.png)

stream ResultSet:
![resultsetstreaming](https://user-images.githubusercontent.com/24643893/39034426-f2fa6d5a-44a8-11e8-9185-5b64e792ead8.png)

Stream ResultSet proved to be more efficiency in space and time.

**Comment by terrymanu** [comment]
fixed at 2.1.0
