### ISSUE TITLE
不兼容spring-boot2.0配置解析

### ISSUE THREAD

**Issue by daijiejay** [shardingjdbc/sharding-jdbc#690]
### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.0.M3
### Expected behavior （您预期的结果是）
兼容spring-boot2.0
### Actual behavior （实际运行的结果是）
spring-boot升级2.0后解析不了这样的配置格式，报错
java.lang.IllegalArgumentException: Could not resolve placeholder '0..1' in value "demo.user_${0..1}"

**Comment by terrymanu** [comment]
duplicate #652
