### ISSUE TITLE
希望开放sql router可自定义

### ISSUE THREAD

**Issue by rjma** [shardingjdbc/sharding-jdbc#693]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

多谢开源这个很棒的项目！

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.3
### Expected behavior （您预期的结果是）
期望可以开发自定义的sql router。
### Actual behavior （实际运行的结果是）
当前代码中，SQLRouterFactory的router创建方法写死了router的类型，想要改写哪怕部分路由算法也需要从data source factory开始继承改写才有可能。

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
    public static SQLRouter createSQLRouter(final ShardingContext shardingContext) {
        return HintManagerHolder.isDatabaseShardingOnly() ? new DatabaseHintSQLRouter(shardingContext) : new ParsingSQLRouter(shardingContext);
    }

希望这部分（或者其他执行路径）能够通过sharding context创建自定义的router，并能够提供配置项。

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by terrymanu** [comment]
I don't get your point. why you need open router API, that is a internal API. And all custimized behaviour should configure by sharding strategy, isn't it?

**Comment by rjma** [comment]
谢谢回复。

主要我们自己有一些特殊的路由需求，涉及内部线上拓扑结构，不便细说。已经有的strategy不全适合我们的场景，而且个人也觉得开放路由算法可自定义，可以提升sharding jdbc的适用广泛性，估计也会有一些场景因为一些局限性需要对路由策略做调整，所以我提出了这个改进申请，主要可以节省我们上千行代码的改写和同步。:)

**Comment by terrymanu** [comment]
Please make all discuss and opinion public. If you cannot provide more details, we can not serve for you.

As my understanding, sharding strategy is totally enough, we want make all api simplify and clear, we don't want provide meaningless api to increase end-users costs.

**Comment by rjma** [comment]
真是很遗憾，权利所限，我无法提供更多的信息了。不过，还是很感谢你们的开源贡献。
