### ISSUE TITLE
suggest shardingjdbc support another placeholder of inline expression

### ISSUE THREAD

**Issue by chidaodezhongsheng** [shardingjdbc/sharding-jdbc#702]
shardingjdbc has supported spring boot 2.0.0 release, however it occured exception when parsing the placeholder of inline expression ${}.
I suggest that it should support another placeholder of inline expression to avoid this similar situation, for example $->{}.
I can pull request for this issue, haha.

**Comment by terrymanu** [comment]
fixed at 3.0.0.M1
