### ISSUE TITLE
java.lang.ClassNotFoundException: groovy.lang.GroovyShell

### ISSUE THREAD

**Issue by wudadadaju** [shardingjdbc/sharding-jdbc#707]
### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.0.M3

### Expected behavior （您预期的结果是）
正常运行

### Actual behavior （实际运行的结果是）
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyShell

### Steps to reproduce the behavior （可重现问题的操作步骤）
启动SpringBootDataJpaMain

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
就是下载的example代码。

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [io/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NoClassDefFoundError: groovy/lang/GroovyShell`

**Comment by wudadadaju** [comment]
是这样的， 我在工作空间中只导入了sharding-jdbc-example、sharding-jdbc-spring-boot-example、sharding-jdbc-spring-boot-data-jpa-example、sharding-jdbc-spring-boot-data-mybatis-example这四个项目，然后运行报那个错误

**Comment by terrymanu** [comment]
为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭
