### ISSUE TITLE
mybatis insert可以插入到分表，find无法从分表查出数据

### ISSUE THREAD

**Issue by fengxiaopeng** [shardingjdbc/sharding-jdbc#709]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.3
### Expected behavior （您预期的结果是）
mybatis可以正常查询
### Actual behavior （实际运行的结果是）
mybatis   insert可以插入到分表，find无法从分表查出数据
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

      @Bean
      public DataSource postgresDataSource() throws Exception {

        ObjectMapper objectMapper = new ObjectMapper();
        org.springframework.core.io.Resource fileResource = new ClassPathResource("shardAlgorithm.json");
        List<ShardAlgorithmDto> shardAlgorithmDtoList = objectMapper.readValue(fileResource.getInputStream(), new TypeReference<List<ShardAlgorithmDto>>() {
        });

        // 配置真实数据源
        Map<String, DataSource> dataSourceMap = new HashMap<>();

        for (ShardAlgorithmDto shardAlgorithmDto : shardAlgorithmDtoList) {
            HikariDataSource dataSource = HikariDataSourceUtil.createDataSource(shardAlgorithmDto.getSchema());
            dataSourceMap.put(shardAlgorithmDto.getMonth(), dataSource);
        }

        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        shardingRuleConfig.getTableRuleConfigs().add(getOrderTableRuleConfiguration(shardAlgorithmDtoList));
        shardingRuleConfig.getBindingTableGroups().add(env.getRequiredProperty(SHARD_TABLE));
        shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new StandardShardingStrategyConfiguration(env.getRequiredProperty(SHARD_SCHEMA_COLUMN), SchemaShardingAlgorithm.class.getName()));
        shardingRuleConfig.setDefaultTableShardingStrategyConfig(new StandardShardingStrategyConfiguration(env.getRequiredProperty(SHARD_TABLE_COLUMN), TableShardingAlgorithm.class.getName()));

        // 获取数据源对象
        DataSource dataSource = ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, new ConcurrentHashMap(), new Properties());

        return dataSource;

    }

     @Bean
     public SqlSessionFactoryBean sqlSessionFactory() throws Exception {
        SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(postgresDataSource());  //上面用sharding-jdbc配置的数据源
        sessionFactory.setTypeAliasesPackage("org.gpscloud.pghandlers");
        sessionFactory.setTypeHandlersPackage("org.gpscloud.pghandlers");
        org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
        configuration.setMapUnderscoreToCamelCase(true);
        sessionFactory.setConfiguration(configuration);
        //mapper文件location
        org.springframework.core.io.Resource[] resources = new PathMatchingResourcePatternResolver().getResources("classpath:/mappings/**/*Mapper.xml");
        sessionFactory.setMapperLocations(resources);
        return sessionFactory;
    }

    // 以下是mapper  insert可以  find 无法查询
    <insert id="insert" parameterType="org.gpscloud.entity.DeviceDataEntity" useGeneratedKeys="true" 
        keyProperty="id">
        INSERT INTO device_data (device_num, version_num, function_code, record_time, sensor_data)
        VALUES (#{deviceNum}, #{versionNum}, #{functionCode}, #{recordTime},
                #{sensorData,javaType=String,jdbcType=OTHER, 
       typeHandler=org.gpscloud.pghandlers.JsonbTypeHandler});
    </insert>

    <select id="findMineLocateList" resultType="org.gpscloud.dto.DeviceLocateDataDto">
        SELECT
            device_num                         AS deviceNum,
            sensor_data ->> 'amaplatitudeNum'  AS amaplatitudeNum,
            sensor_data ->> 'latitudeName'     AS latitudeName,
            sensor_data ->> 'amaplongitudeNum' AS amaplongitudeNum,
            sensor_data ->> 'longitudeName'    AS longitudeName,
            sensor_data ->> 'locateDateTime'   AS locateDateTime,
            sensor_data ->> 'totalMileage'     AS totalMileage
        FROM device_data
        WHERE device_num = #{deviceNum}
              AND sensor_data ->> 'locateStatus' = 'A'
              AND sensor_data ->> 'gpsSpeed' != '0'
              AND record_time BETWEEN #{startDate} AND #{endDate}
        ORDER BY record_time DESC;

    </select>

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by terrymanu** [comment]
为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭
