### ISSUE TITLE
没有配置table-rule的表， 不能使用OR 等语句

### ISSUE THREAD

**Issue by neil4dong** [shardingjdbc/sharding-jdbc#734]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
1.5.41
### Expected behavior （您预期的结果是）
没有配置分表的表，能够使用一切SQL语句， 包含OR等sharding jdbc不支持的语句
### Actual behavior （实际运行的结果是）
不支持OR
### Steps to reproduce the behavior （可重现问题的操作步骤）

> <rdb:data-source id="shardingDataSource">
        <rdb:sharding-rule data-sources="masterDataSource">
            <rdb:table-rules>
                <rdb:table-rule logic-table="order" actual-tables="order_${0..9}${0..9}" table-strategy="tableShardingStrategy"/>
                <rdb:table-rule logic-table="amount_detail" actual-tables="amount_detail_${0..9}${0..9}" table-strategy="tableShardingStrategy"/>
            </rdb:table-rules>
        </rdb:sharding-rule>
        <rdb:props>
            <prop key="metrics.enable">false</prop>
            <prop key="sql.show">false</prop>
        </rdb:props>
    </rdb:data-source>

然后查询 一个没有在这里配置的table，并且使用OR

**Comment by terrymanu** [comment]
duplicate with #621
