### ISSUE TITLE
结合spring配置 sharding:table-rule ，万恶的写法。

### ISSUE THREAD

**Issue by wgou** [shardingjdbc/sharding-jdbc#738]
<sharding:table-rule logic-table="reb_sale" 
                actual-data-nodes="rebate_datasource.reb_sale_000,rebate_datasource.reb_sale_001,rebate_datasource.reb_sale_002,rebate_datasource.reb_sale_003,rebate_datasource.reb_sale_004,rebate_datasource.reb_sale_005,rebate_datasource.reb_sale_006,
                				  rebate_datasource.reb_sale_007,rebate_datasource.reb_sale_008,rebate_datasource.reb_sale_009,rebate_datasource.reb_sale_010,rebate_datasource.reb_sale_011,rebate_datasource.reb_sale_012,rebate_datasource.reb_sale_013,
                				  rebate_datasource.reb_sale_014,rebate_datasource.reb_sale_015,rebate_datasource.reb_sale_016,rebate_datasource.reb_sale_017,rebate_datasource.reb_sale_018,rebate_datasource.reb_sale_019" 
                table-strategy-ref="rebSaleStrategy"/>

因为${} 与spring冲突，分表100张改如何是好？

**Comment by terrymanu** [comment]
please read document first

**Comment by wgou** [comment]
releases 中没有2.1版本。2.1.0 版本任然在dev分支继续开发中，请问什么时候可以对2.1.0封版呢？
