### ISSUE TITLE
不支持springboot2.0

### ISSUE THREAD

**Issue by cxyzjp** [shardingjdbc/sharding-jdbc#740]
### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
Sharding-Jdbc版本：2.0.3
### Expected behavior （您预期的结果是）
希望可以集成到springboot2.0
### Actual behavior （实际运行的结果是）
报错：java.lang.ClassNotFoundException: org.springframework.boot.bind.RelaxedPropertyResolver

原因springboot2.0中RelaxedPropertyResolver不再可用了

**Comment by terrymanu** [comment]
duplicate #652
