### ISSUE TITLE
可以按地理位置分表吗，并且做成自动生成表的功能模块，集成到sharding-jdbc

### ISSUE THREAD

**Issue by tianxia007** [shardingjdbc/sharding-jdbc#751]
比如业务部order，如果要对order按地理位置分表：自动生成
order_省会名_市名_1....
再有个表维护多个字表的关联关系，可以自动生成汇总sql，如求山东省所有订单：
自动生成：select * from order_shandong_jinan_1 union all select * from order_shandong_langfang_1 ....

~~~

**Comment by terrymanu** [comment]
yes, sharding strategies are user-defined, you can do every thing in java code or inline expression.
