### ISSUE TITLE
默认提供了DefaultKeyGenerator的实现，但是如何指定workerId？

### ISSUE THREAD

**Issue by Mailerm** [shardingjdbc/sharding-jdbc#762]
默认提供了DefaultKeyGenerator的实现，但是如何指定workerId？

1. KeyGeneratorFactory 未发现动态设置；
2. ShardingRule里面也没有方法可以获取到KeyGenerator实例。

**Comment by terrymanu** [comment]
You may find solution on document, text below is from document:

This flag is unique in the Java process, and you should ensure that every process ID is different in distributed applications. The default value is 0, and can be configured by calling `DefaultKeyGenerator.setWorkerId("xxxx")`.
