### ISSUE TITLE
shardingjdbc datasource能否针对非路由的表，sql解析时不做兼容性检查

### ISSUE THREAD

**Issue by chncho** [shardingjdbc/sharding-jdbc#766]
### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.3

### Expected behavior （您预期的结果是）
shardingjdbc datasource能否针对非路由的表，sql解析时不做兼容性检查

### Actual behavior （实际运行的结果是）
shardingjdbc datasource针对非路由的表，sql解析时会对不兼容的sql报错

### Steps to reproduce the behavior （可重现问题的操作步骤）
shardingjdbc datasource针对非路由的表，sql解析时会对不兼容的sql报错

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
shardingjdbc datasource能否针对非路由的表，sql解析时不做兼容性检查
``` xml
<select id="find" resultMap="baseResultMap">
        select * from t_order
        where count_date>=#{from,jdbcType=TIMESTAMP}
        and count_date &lt; #{to,jdbcType=TIMESTAMP}
        and (status is null or satus='FALSE')
    </select>
 <sharding:complex-strategy id="orderTableShardingStrategy"  sharding-columns="id,count_date,systemflowid" algorithm-class="io.shardingjdbc.exampleExt.spring.namespace.mybatis.algorithm.PreciseTableComplexShardingAlgorithm"/>
    <sharding:none-strategy id="orderTableNoneShardingStrategy" />
```
``` xml
    <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule data-source-names="demo_ds4sharding" default-data-source-name="demo_ds4sharding" default-table-strategy-ref="orderTableNoneShardingStrategy">
            <sharding:table-rules>
                <sharding:table-rule logic-table="logic_t_order" actual-data-nodes="demo_ds4sharding.t_order_${['2018','2019']}${['01','02','03','04','05','06','07','08','09','10','11','12']}"
                                     table-strategy-ref="orderTableShardingStrategy" />
            </sharding:table-rules>
            <sharding:binding-table-rules>
                <sharding:binding-table-rule logic-tables="logic_t_order"/>
                <!--<sharding:binding-table-rule logic-tables="t_order, t_order_item"/>-->
            </sharding:binding-table-rules>
        </sharding:sharding-rule>
        <sharding:props>
            <prop key="sql.show">true</prop>
        </sharding:props>
    </sharding:data-source>
```
Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by terrymanu** [comment]
duplicated with #659

**Comment by chncho** [comment]
方法1：配置default-data-source，凡是在默认数据源中的表可以无需配置在分片规则中，Sharding-JDBC将在找不到分片数据源的情况下将表路由至默认数据源。
【该方法，不路由的表，也会有sql兼容性检查，对于不支持的sql会报异常】
方法2：将不参与分库分表的数据源独立于Sharding-JDBC之外，在应用中使用多个数据源分别处理分片和不分片的情况。
【该方法，程序中会存在两个数据源，两个数据源之间无法保证事务一致性】
