### ISSUE TITLE
where条件紧跟两个左括号 (  ，无法识别分片条件

### ISSUE THREAD

**Issue by qchen006** [shardingjdbc/sharding-jdbc#769]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.3
### Expected behavior （您预期的结果是）
sql语句中 where ((    含有两个左括号，也能够根据where条件的内容正确分片
### Actual behavior （实际运行的结果是）
sql语句中 where ((    含有两个左括号，where条件的内容就无法分片
### Steps to reproduce the behavior （可重现问题的操作步骤）
假设分片条件是： col1 的列取值
正常情况下 select * from tbl_a where (col1= 'a') 是可以根据col1的值进行分片
但是如果，where后面紧跟两个左括号
select * from tbl_a where ((col1= 'a'))  就无法进行分片

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by terrymanu** [comment]
Cannot support `brackets redundancy`. Please read document before submit a issue, thank you.
