### ISSUE TITLE
针对文档中提到的两个解决不需要分表的处理方法分别有以下缺陷，请问有没有方法解决

### ISSUE THREAD

**Issue by chncho** [shardingjdbc/sharding-jdbc#770]
针对文档中提到的两个解决不需要分表的处理方法分别有以下缺陷，请问有没有方法解决
方法1：配置default-data-source，凡是在默认数据源中的表可以无需配置在分片规则中，Sharding-JDBC将在找不到分片数据源的情况下将表路由至默认数据源。
【该方法，不路由的表，也会有sql兼容性检查，对于不支持的sql会报异常】
方法2：将不参与分库分表的数据源独立于Sharding-JDBC之外，在应用中使用多个数据源分别处理分片和不分片的情况。
【该方法，程序中会存在两个数据源，两个数据源之间无法保证事务一致性】

**Comment by terrymanu** [comment]
we can't promise ACID transaction on distribute database, we just use BASE transaction.

**Comment by chncho** [comment]
但是，当仅分表，不分库的时候，是不必要去引入 分布式这样 不一致性的处理的，其实我的问题主要是针对 “方法1：配置default-data-source，凡是在默认数据源中的表可以无需配置在分片规则中，Sharding-JDBC将在找不到分片数据源的情况下将表路由至默认数据源。
【该方法，不路由的表，也会有sql兼容性检查，对于不支持的sql会报异常】” 这个，这块能否针对不路由的表放宽限制

**Comment by chncho** [comment]
比如，解析的时候先解析有哪些表，解析完有哪些表之后，再看他有没有路由规则，路由规则是不是None，如果是这样，就不走后面的解析，而是直接执行sql语句即可
