### ISSUE TITLE
分库分表添加主从配置报错，Cannot find data source in sharding rule, invalid actual data node is

### ISSUE THREAD

**Issue by moxingwang** [shardingjdbc/sharding-jdbc#774]
<sahrding.latest.release.version>2.0.3</sahrding.latest.release.version>

`
public Map<String, DataSource> getDataSourceMap() {
        Map<String, DataSource> dataSourceMap = new HashMap<>(2, 1);

        dataSourceMap.put("tx_order_master_0", dataSourceMaster0());
        dataSourceMap.put("tx_order_master_1", dataSourceMaster1());
        dataSourceMap.put("tx_order_slave_0", dataSourceSlave0());
        dataSourceMap.put("tx_order_slave_1", dataSourceSlave1());
        return dataSourceMap;
    }

    @Bean
    public DataSource getShardingDataSource() throws SQLException, IOException {

        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        shardingRuleConfig.setDefaultDataSourceName("tx_order_master_0");
        shardingRuleConfig.getTableRuleConfigs().addAll(getTableRuleConfigurations());

        // 构建读写分离配置
        MasterSlaveRuleConfiguration masterSlaveRuleConfig0 = new MasterSlaveRuleConfiguration();
        masterSlaveRuleConfig0.setName("tx_order_master_slave_0");
        masterSlaveRuleConfig0.setMasterDataSourceName("tx_order_master_0");
        masterSlaveRuleConfig0.getSlaveDataSourceNames().add("tx_order_slave_0");

        MasterSlaveRuleConfiguration masterSlaveRuleConfig1 = new MasterSlaveRuleConfiguration();
        masterSlaveRuleConfig1.setName("tx_order_master_slave_1");
        masterSlaveRuleConfig1.setMasterDataSourceName("tx_order_master_1");
        masterSlaveRuleConfig1.getSlaveDataSourceNames().add("tx_order_slave_1");

        shardingRuleConfig.getMasterSlaveRuleConfigs().add(masterSlaveRuleConfig0);
        shardingRuleConfig.getMasterSlaveRuleConfigs().add(masterSlaveRuleConfig1);

        shardingRuleConfig.getBindingTableGroups().add(SHARDING_TABELS + "," + INDEP_TABELS);
        shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("sharding_key", PreciseDatabaseShardingAlgorithm.class.getName()));
        shardingRuleConfig.setDefaultTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("sharding_key", PreciseTableShardingAlgorithm.class.getName()));
        Properties props = new Properties();
        props.setProperty(ShardingPropertiesConstant.SQL_SHOW.getKey(), "true");

        return ShardingDataSourceFactory.createDataSource(getDataSourceMap(), shardingRuleConfig, new HashMap<String, Object>(), props);
    }

`

**Comment by moxingwang** [comment]
看源码dataSourceMap.remove(each.getMasterDataSourceName());，dataSourceMap被remove掉了，不明白我的配置哪里不对

` public ShardingRule build(final Map<String, DataSource> dataSourceMap) throws SQLException {
        Preconditions.checkNotNull(dataSourceMap, "dataSources cannot be null.");
        Preconditions.checkArgument(!dataSourceMap.isEmpty(), "dataSources cannot be null.");
        processDataSourceMapWithMasterSlave(dataSourceMap);
        Collection<TableRule> tableRules = new LinkedList<>();
        for (TableRuleConfiguration each : tableRuleConfigs) {
            tableRules.add(each.build(dataSourceMap));
        }
        ShardingStrategy defaultDatabaseShardingStrategy = null == defaultDatabaseShardingStrategyConfig ? null : defaultDatabaseShardingStrategyConfig.build();
        ShardingStrategy defaultTableShardingStrategy = null == defaultTableShardingStrategyConfig ? null :  defaultTableShardingStrategyConfig.build();
        KeyGenerator keyGenerator = KeyGeneratorFactory.newInstance(null == defaultKeyGeneratorClass ? DefaultKeyGenerator.class.getName() : defaultKeyGeneratorClass);
        return new ShardingRule(dataSourceMap, defaultDataSourceName, tableRules, bindingTableGroups, defaultDatabaseShardingStrategy, defaultTableShardingStrategy, keyGenerator);
    }
    
    private void processDataSourceMapWithMasterSlave(final Map<String, DataSource> dataSourceMap) throws SQLException {
        for (MasterSlaveRuleConfiguration each : masterSlaveRuleConfigs) {
            dataSourceMap.put(each.getName(), MasterSlaveDataSourceFactory.createDataSource(dataSourceMap, each, Collections.<String, Object>emptyMap()));
            dataSourceMap.remove(each.getMasterDataSourceName());
            for (String slaveDataSourceName : each.getSlaveDataSourceNames()) {
                dataSourceMap.remove(slaveDataSourceName);
            }
        }
    }`

**Comment by terrymanu** [comment]
We are glad to see you find the solution by yourself.

**Comment by moxingwang** [comment]
`
shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("sharding_key", PreciseDatabaseShardingAlgorithm.class.getName()));
    shardingRuleConfig.setDefaultTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("sharding_key", PreciseTableShardingAlgorithm.class.getName()));

`
这里错了，InlineShardingStrategyConfiguration应该换成StandardShardingStrategyConfiguration
