### ISSUE TITLE
能否针对不路由的表放宽限制

### ISSUE THREAD

**Issue by chncho** [shardingjdbc/sharding-jdbc#783]
当仅分表，不分库的时候，是不必要去引入 分布式这样 不一致性的处理的，其实我的问题主要是针对 “方法1：配置default-data-source，凡是在默认数据源中的表可以无需配置在分片规则中，Sharding-JDBC将在找不到分片数据源的情况下将表路由至默认数据源。
【该方法，不路由的表，也会有sql兼容性检查，对于不支持的sql会报异常】” 这个，这块能否针对不路由的表放宽限制.
比如，解析的时候先解析有哪些表，解析完有哪些表之后，再看他有没有路由规则，路由规则是不是None，如果是这样，就不走后面的解析，而是直接执行sql语句即可

**Comment by terrymanu** [comment]
Sorry, we can not do on this way.

We must use parse engine to adjust table in SQL is in default datasource or not. If some syntax cannot support, we will throw an exception and terminate parse. So you said `if in default datasource, then skip verify...` in impassable.

Actually, we don'y have SQL verify phase, we just throw an exception when meet unsupported SQL.
