### ISSUE TITLE
[Vote] Change project name from Sharding-JDBC to Sharding-Sphere

### ISSUE THREAD

**Issue by terrymanu** [shardingjdbc/sharding-jdbc#788]
Sharding by JDBC layer only is not enough for diversified scenario. For example: dev language excepted Java, entry for database command client or UI. Because of the reasons, we dev anther proxy solution, the name of `Sharding-JDBC` is not suitable any more.

Because of `Sharding-JDBC` is well-known at the past 2 years, we can not give up this intellectual property, so we want keep the key word `Sharding` as well, just move `Sharding-JDBC`, the new project `Sharding-Proxy` and `Sharding-Sidecar`(incubation now, for kubernetes env) in an ecosphere together, We call them as `Sharding-Sphere`.

The vote is for All Initial Committers:

@shardingjdbc/committers 
@ma-xiao-guang-64 
@CharlesMaster 
@YunaiV 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

**Comment by CharlesMaster** [comment]
agree, yes, +1

**Comment by YunaiV** [comment]
agree, yes, +1

**Comment by wu-sheng** [comment]
FYI this vote will open in at least a week. Welcome any contributor, end user and interested people to express themselves.

**Comment by hanahmily** [comment]
agree,yes,+1

**Comment by gaoyaqiu** [comment]
agree, yes, +1

**Comment by qiankunshe** [comment]
agree, yes, +1

**Comment by chenhaifeng2016** [comment]
agree, yes, +1

**Comment by yikangfeng** [comment]
agree, yes, +1

**Comment by low901028** [comment]
agree, yes, +1

**Comment by sagkanon** [comment]
agree, yes, +1

**Comment by Alanlxh** [comment]
abstain

**Comment by duerlatter** [comment]
agree, yes, +1

**Comment by tianbin1001** [comment]
agree, yes, +1

**Comment by learndockering** [comment]
agree, yes, +1

**Comment by nature9007** [comment]
agree，yes， +1

**Comment by himalayaRange** [comment]
agress , yes , +1

**Comment by osbornjonny** [comment]
agree, yes, +1

**Comment by yjmyzz** [comment]
agree, yes, +1

**Comment by chengchenrui** [comment]
agree, yes, +1

**Comment by chinacode** [comment]
+1

**Comment by kiddyt00** [comment]
agree，yes，+1

**Comment by kuangzuoqiang** [comment]
agree, yes, +1

**Comment by lvxinrong** [comment]
agree, yes, +1

**Comment by gufengwyx8** [comment]
disagree, no, -1

**Comment by gufengwyx8** [comment]
agree, yes, +1

**Comment by tristaZero** [comment]
agree, yes, +1

**Comment by LingLiYuki** [comment]
agree, yes, +1

**Comment by wangda** [comment]
agree, yes, +1

**Comment by lipeng1234** [comment]
agree, yes, +1

**Comment by zhuokun** [comment]
agree, yes, +1

**Comment by orangeyts** [comment]
agree, yes, +1

**Comment by wu-sheng** [comment]
@terrymanu I think we should close this vote today.

FYI, remind you, @shardingjdbc/committers doesn't match organization in website http://shardingsphere.io/community/en/organization/ 

We should fix this.

**Comment by terrymanu** [comment]
@wu-sheng wu OK. Thank you for remind, I will update now.

**Comment by terrymanu** [comment]
Thanks for every voter, the vote is success and close now.
We received 39 agree, 1 abstain and zero disagree,  initial committers are all agree.
We will begin procedure about rename.

Thank you very much.

**Comment by wangdan0-0** [comment]
sharding作为整个品牌的名称，然后项目里面又有一些专门的角色叫做sharding，稍感觉有点那啥
重庆省 重庆市 重庆乡 的感觉
但这说起来就是后话了
